### PR TITLE
Modified radio-group onKeydown to use existing helper

### PR DESCRIPTION
**Pull request by danielsimao**
Make onKeydown function use already existing helper that lists all radios inside group

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- No new behaviour

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by danielsimao** [comment]
Any ideia why vue tests fails with this change?

**Review by liamdebeasi — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Thanks for the PR! I am not sure why Circle CI is not running tests. I checked the webhook for this and it was delivered successfully. I opened a new PR with this commit, so I will give you co-author credit there. I will close this out once the other PR is merged.

**Comment by danielsimao** [comment]
> Thanks for the PR! I am not sure why Circle CI is not running tests. I checked the webhook for this and it was delivered successfully. I opened a new PR with this commit, so I will give you co-author credit there. I will close this out once the other PR is merged.

@liamdebeasi thank you so much for the quick response. It's actually the first time I do something for open-source! It ain't much but it's honest work. 😆 Have a nice day!

**Comment by liamdebeasi** [comment]
Thank you! I just merged this fix via https://github.com/ionic-team/ionic-framework/pull/23396 and gave you co-author credit in https://github.com/ionic-team/ionic-framework/commit/d527414e109c9cc6ae43171911f89a43b2f0691f.

**Pull request closed without merging**
