### PR TITLE
[React] ssr ReferenceError: document is not defined

### PR DESCRIPTION
**Pull request by wis**
When using react output generated components do not work in ssr (like Next.js) because generated component try to use document without safety checking if document exists. 

default function parameters values of built in globals is not a good pattern to use when SSR support is a goal of the project, so can you https://www.youtube.com/watch?v=4gYZsCm5blA :)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

`ReferenceError: document is not defined` when SSRing

Issue Number: N/A

## What is the new behavior?

no `ReferenceError: document is not defined`
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! Can you fix the failing test?

**Comment by wis** [comment]
I fixed all the failing tests that I could, only one is left `test-core-clean-build` I don't know what it is for, it seems to be a `git diff` command that exits with code 0 and makes test fail if it has output.

**Comment by liamdebeasi** [comment]
Try syncing your branch with the latest `master` and pushing those changes. We recently updated Swiper which is probably why you are getting that failure.

**Comment by wis** [comment]
done, all tests pass now.

**Comment by liamdebeasi** [comment]
Hmm since you forked Ionic, it looks like you will need to a) sync your fork's `master` branch with our `master` branch and b) sync your PR branch with your fork's `master`.

This StackOverflow answer gives a pretty good walkthrough of how to do it: https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

Or if it's easier, just refork from Ionic and copy your changes over so you have the latest changes in Ionic.

**Comment by liamdebeasi** [comment]
Apologies for the delay. It looks like this issue was resolved when we shipped our `@ionic/react-router` enhancements in v5.3.0: https://github.com/ionic-team/ionic-framework/blob/master/packages/react/src/components/utils/attachProps.ts#L70

I am going to close this PR, but feel free to open an issue if you run into any other problems with SSR. Thanks!

**Pull request closed without merging**
