### PR TITLE
fix(button): allow any element type to to use the "icon-only" slot

### PR DESCRIPTION
**Pull request by bitflower**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

Not sure if this has or needs a test?

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
Only `ion-icon` are recognized inside the slots to indicate the button's `iconOnly` mode.

## What is the new behavior?
Any element with `slot='icon-only'` is recognized.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bitflower** [comment]
Use case: Avatar image (for example @shoelace's `sl-avatar`) in an `ion-toolbar`:
image

**Comment by liamdebeasi** [comment]
Thanks for the PR! Could you please provide a code example of the use case in https://github.com/ionic-team/ionic-framework/pull/22168#issuecomment-698559472 that highlights the current issues you are running into with `icon-only`?

**Comment by bitflower** [comment]
Sure, I want to use the component `sl-avatar` from the Shoelace Design System. It's has the appearance of an icon = round. That's why I want to treat it as `icon-only` to center it inside the button.

Sample code to my example image from the comment above:
```
<ion-button>
   <sl-avatar slot='icon-only' />
</ion-button>
```

**Comment by liamdebeasi** [comment]
Thanks! It sounds like you are mostly interested in ensuring that the ripple effect correctly covers the `sl-avatar` component?

**Comment by bitflower** [comment]
a) the covering wold be nice but b) having a round ripple is more important. Right now it's a rectangle.

**Review by brandyscarney — APPROVED** [review]

**Pull request merged**
