### PR TITLE
chore(ci): enable fail-fast for matrix jobs

### PR DESCRIPTION
**Pull request by liamdebeasi**
Screenshot matrix jobs had "fail-fast: false". This enabled each test runner to provide its `playwright-report` directory as an artifact so team members can view test failures. At the time, all tests ran even if previous tests failed.

In https://github.com/ionic-team/ionic-framework/pull/26447, we updated the Playwright config to have tests fail fast within a single test runner. However, other test runners continue to run. This is not helpful in the case of failing tests because the artifacts for each test runner will not be reported until all test runners are done.

This PR changes the matrix strategy to enable fail-fast (which is the default) so in-progress/queued test runners fail if a previous test runner fails.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by amandaejohnston** [comment]
Wouldn't this mean that if one test fails, we may not see the results for the others even if there are other failures? I.e. we'd have to run everything multiple times to catch all the failing tests.

**Comment by liamdebeasi** [comment]
Yes, if there are multiple failures you will potentially not see every error the first time. However, this is true today since individual test runners fail fast. There are a few reasons why I think the proposed behavior is desirable:

1. Developers should be running tests locally before pushing their changes. (i.e. bad tests that repro locally should be caught before pushing to the repo)
2. Test runners run the same test multiple times (different configs: ios, md, ltr, rtl, etc) so the same failure can pop up on multiple test runners. Waiting for those subsequent failures does not give us additional information.
3. GitHub does not let us access the artifacts for each test runner in a matrix until all test runners are done (at least as far as I can tell). This means that even though a test runner fails fast, you still need to wait for all the runners to complete to download the `playwright-report` directory.


I'm trying to find ways to get CI feedback to team members quickly, so I'm open to other ideas too. I suppose where this could get tricky is when you have multiple distinct unintentional regressions. However, my experience has been that item 2 above happens more frequently than multiple distinct unintentional regressions.

**Review by amandaejohnston — APPROVED** [review]
Makes sense to me. Plus we can always revert the change if it causes problems.

**Comment by liamdebeasi** [comment]
Adding Sean as a reviewer so I can get buy-in from the entire team.

**Review by sean-perkins — APPROVED** [review]
I'm in favor of trying out this change. In many instances I find the same test failing across multiple jobs, so tying up CI for the remainder of the run is not beneficial.

**Comment by liamdebeasi** [comment]
Blocked on https://github.com/ionic-team/ionic-framework/pull/26731. This resolves a handful of the more common flaky tests, so would like to get this in first.

**Pull request merged**
