### PR TITLE
refactor(virtual-scroll): deprecate virtual scroll in favor of JS framework solutions

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): deprecation

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by avidan-chen** [comment]
Very disappointed in this decision. ion-virtual-scroll is the only component we found to work well with pull to refresh and dynamic sizes (using Angular). With this decision, we are left with no solution for variable height items (we tried to migrate to different open source Angular components, in a process that spanned from than a few weeks, no component came close to Ionic's implementation, even considereing the open bugs this component has).
In my opinion, given that this is the only solution available for Angular / Ionic developers needing to implement a virtual scroll with variable height items, it would have been preferable to work on the open issues rather than deprecate it and leave us hanging.

**Comment by MuhAssar** [comment]
@avidan-chen :
I had a similar experiece  like yours, I tried using Angular Materials's virtual-scroll but found that ion-virtual-scroll  is a better solution.
@liamdebeasi :
I hope you keep ion-virtual-scroll as a community supported component and call for a volunteer to maintain it.

**Comment by elvisgraho** [comment]
Been using 'ngx-virtual-scroller' for Angular. Fixed all the issues. The deprecation of ion-virtual-scroll doesn't affect pull to refresh (ion-refresher) at all.

**Comment by avidan-chen** [comment]
@elvisgraho 
Tried that. Had multiple issues with it, couldn't sort it out. Weird jumps while scrolling, UI didn't always look good. Perhaps we had different layouts to each item, so we got different results. Either way, ion-virtual-scroll was the only one we could get to work with our requirements.

**Pull request merged**
