### PR TITLE
docs(modal): add correct card-style modal usage for react

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21773

## What is the new behavior?

- Updated usage to pass in IonRouterOutlet ref

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pritamsoni-hsr** [comment]
this one is not working properly, see [this](https://youtu.be/dVzX_MG1pdg)

**Comment by liamdebeasi** [comment]
You might need to do `routerRef.current.current`. React sometimes gives back a nested ref for `IonRouterOutlet`.

**Comment by pritamsoni-hsr** [comment]
@liamdebeasi when modal is presented in card style, color of status bar should change, any plan of adding that to ionic-core?

**Comment by liamdebeasi** [comment]
See https://github.com/ionic-team/ionic-framework/issues/20501

**Comment by pritamsoni-hsr** [comment]
with 5.3.1 update, routerRef.current will work.

**Comment by liamdebeasi** [comment]
I'll make a PR to update the docs. Thanks!

**Pull request merged**
