### PR TITLE
fix(vue): ionic lifecycle hooks now run when using vue 3.2 setup syntax

### PR DESCRIPTION
**Pull request by snowwolfjay**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number:  #23824

## What is the new behavior?

Define a property on vue instance exposed source object make the hooks be public then they can be access and fire;
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! We appreciate the work you put in to create this fix. In order for this PR to be accepted, can you please add some tests to verify this new behavior? It might be easiest to add some tests to the `lifecycle.spec.ts` file: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/test-app/tests/unit/lifecycle.spec.ts

**Comment by snowwolfjay** [comment]
> Thanks for the PR! We appreciate the work you put in to create this fix. In order for this PR to be accepted, can you please add some tests to verify this new behavior? It might be easiest to add some tests to the `lifecycle.spec.ts` file: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/test-app/tests/unit/lifecycle.spec.ts

ok.

**Comment by snowwolfjay** [comment]
sadly , I still can't find a way to simulate the case when use script-setup sugar, looks like used additional compile to handle codes which test-utils not cover those part . Will check later.
If any idea please tell and help , thanks. 

 Before that, ^_^ anyone meet this case ,just need copy changes to  local

**Review by riderx — APPROVED** [review]

**Review by liamdebeasi — APPROVED** [review]
I ended up adding some E2E tests. This PR is good to merge when all the tests pass. Thank you for submitting this!

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Comment by Dangerous828** [comment]
这个issue有一个问题，跟着最新的文档提供的vite ionic搭建方式，然后移除ts之后无法也无法正常使用生命周期和 script setup

**Comment by Dangerous828** [comment]
This issue has a problem with following the latest documentation on how to build vite ionic, and then removing ts does not and cannot work properly with the lifecycle and script setup. #28681

**Pull request merged**
