### PR TITLE
fix(action-sheet): remove height property from css class .action-sheet-title

### PR DESCRIPTION
**Pull request by msigwart**
fix(action-sheet): remove height property from css class .action-sheet-title

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #17588

## What is the new behavior?

- Options of ActionSheet do not overlay a long subtitle on Android

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! 🙂 So the only problem I am seeing is that the spacing top isn't there when there are a lot of buttons and the height is missing:

| Without `height` | `height: 60px` |
| ---| ---|
| localhost_3333_src_components_action-sheet_test_basic(Galaxy S5) | localhost_3333_src_components_action-sheet_test_basic(Galaxy S5) (1) |

I need to verify if this is still desired.

**Comment by msigwart** [comment]
Any updates?

**Comment by tobika** [comment]
Hi @adamdbradley, did you verify the issue about the missing top spacing? I stumbled over this problem and for the moment used the fix to remove the height property

**Comment by liamdebeasi** [comment]
Thank you for the PR, and apologies for the delay. We appreciate you taking the time to open up a PR on our repo.

It looks like the related issue was already resolved in https://github.com/ionic-team/ionic-framework/pull/23318, so this PR is no longer needed. The fix is available starting in [Ionic v5.6.8](https://github.com/ionic-team/ionic-framework/releases/tag/v5.6.8).

I am going to close this. Thanks!

**Pull request closed without merging**
