### PR TITLE
feat(action-sheet, alert): add id to AlertButton and ActionSheetButton

### PR DESCRIPTION
**Pull request by devinshoemaker**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

There is currently no way to add an ID to an `AlertButton`, which would be particularly useful for writing automated tests.

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22959

## What is the new behavior?

- The `AlertButton` interface now has an optional `id` property that will be added to the HTML button when rendered.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devinshoemaker** [comment]
It looks like this PR failed on a couple of tests, and I would like some insight into why so that I can get this PR updated if need be. `test-angular-e2e` failed on `E/launcher - session not created: Chrome version must be between 71 and 75` which appears to be an issue with the CircleCI environment. `test-core-clean-build` appears to have failed for there being a diff on the readme that I updated without any insight into why.

**Comment by devinshoemaker** [comment]
Hey Ionic team, I just wanted to check back in to see if I could get some eyes on this. I think that this is a pretty obvious feature and seems to compliment the surrounding code that is already in place. This would also help me and likely many others in e2e testing and such.

**Comment by DanielFroehlich** [comment]
+1 I would love to have this, too!

**Comment by SalahAdDin** [comment]
@devinshoemaker What happened about this?

I was thinking about opening a new feat request to enable custom properties on **AlertButton**, but I saw yours and I think it is enough.

We required this in order to ease the automation test: right now we are getting buttons by classes but it makes things hard to handle, to making this easier we are applying the **[Cypress](https://docs.cypress.io/guides/references/best-practices.html#How-It-Works)** best practices, but we can't put `data-cy` property to **AlertButtons**. 

We think your feat can help us to solve this problem.

**Review by liamdebeasi — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
