### PR TITLE
fix(colors): change ionic colors scss imports for ionic dist

### PR DESCRIPTION
**Pull request by BenOsodrac**
Issue number: internal

---------

## What is the current behavior?

When consuming the Ionic Framework and using the Ionic Theme, the color attribute was still not working as the color css was not present.

## What is the new behavior?

- Now the ion-color maps are correctly imported on the Ionic `dist` related folder and not the on the `md/ios` ones.
- Changed the usage of `map.get` to `map-get` to avoid issues with the usage of `@use` and `@forward`. This seems to have no impact on the compilation and I believe its a better code convention, as map-gets are a native scss function that doesn't need to be imported.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by OS-giulianasilva — APPROVED** [review]

**Review by thetaPC — COMMENTED** [review]
Screenshot 2024-08-23 at 8 39 35 AM

When I set the theme to `ionic`, the colors don't match. For example, the button primary base is rendering with `md/iOS` primary instead of `ionic`.

**Comment by BenOsodrac** [comment]
> Screenshot 2024-08-23 at 8 39 35 AM
> 
> When I set the theme to `ionic`, the colors don't match. For example, the button primary base is rendering with `md/iOS` primary instead of `ionic`.

@thetaPC I believe that happens because of the CSS files that are imported on the test files used by ionic/md/ios. In this case only the md/ios bundle is imported:
Screenshot 2024-08-23 at 17 11 07

But we should be importing for Ionic the `"../../../../../css/ionic/bundle.ionic.css"`, as we have separate distribution CSS files.

In my opinion, this is a bigger topic that should be reviewed in all common tests (or we let it be until future decisions are made)

**Comment by thetaPC** [comment]
Threading the [conversation](https://github.com/ionic-team/ionic-framework/pull/29791#issuecomment-2307400086) here:

I was able to confirm that switching from `<link href="../../../../../css/ionic.bundle.css" rel="stylesheet" />` to `<link href="../../../../../css/ionic/bundle.ionic.css" rel="stylesheet" />` does display the correct colors.

In order for the test pages and snapshots to display correct, let's also update the `core/scripts/testing/scripts.js`:
```diff
 // core/scripts/testing/scripts.js
if (palette && palette[1] !== 'light') {
  const linkTag = document.createElement('link');
  linkTag.setAttribute('rel', 'stylesheet');
  linkTag.setAttribute('type', 'text/css');
  linkTag.setAttribute('href', `/css/palettes/${palette[1]}.always.css`);
  document.head.appendChild(linkTag);
}

+ /**
+  * The `ionic` theme uses a different stylesheet than the `iOs` and `md` themes.
+  * This is to ensure that the `ionic` theme is loaded when the `ionic:theme=ionic`
+  * and makes sure that the snapshot tests are rendered correctly.
+  */
+ const theme = window.location.search.match(/ionic:theme=([a-z]+)/);
+ if (theme && theme[1] === 'ionic') {
+   const linkTag = document.querySelector('link[href*="css/ionic.bundle.css"]');
+   const ionicThemeLinkTag = document.querySelector('link[href*="css/ionic/bundle.ionic.css"]');
+   if (!linkTag || ionicThemeLinkTag) {
+     return;
+   }
+   linkTag.setAttribute('href', linkTag.getAttribute('href').replace('ionic.bundle.css', 'ionic/bundle.ionic.css'));
+ }

window.Ionic = window.Ionic || {};
```

**Comment by thetaPC** [comment]
Threading the [conversation](https://github.com/ionic-team/ionic-framework/pull/29791#issuecomment-2307400086) here:

@BenOsodrac  I was able to confirm that switching from `<link href="../../../../../css/ionic.bundle.css" rel="stylesheet" />` to `<link href="../../../../../css/ionic/bundle.ionic.css" rel="stylesheet" />` does display the correct colors.

In order for the test pages and snapshots to display correct, let's also update the `core/scripts/testing/scripts.js`:
```diff
 // core/scripts/testing/scripts.js
if (palette && palette[1] !== 'light') {
  const linkTag = document.createElement('link');
  linkTag.setAttribute('rel', 'stylesheet');
  linkTag.setAttribute('type', 'text/css');
  linkTag.setAttribute('href', `/css/palettes/${palette[1]}.always.css`);
  document.head.appendChild(linkTag);
}

+ /**
+  * The `ionic` theme uses a different stylesheet than the `iOs` and `md` themes.
+  * This is to ensure that the `ionic` theme is loaded when the `ionic:theme=ionic`
+  * and makes sure that the snapshot tests are rendered correctly.
+  */
+ const theme = window.location.search.match(/ionic:theme=([a-z]+)/);
+ if (theme && theme[1] === 'ionic') {
+   const linkTag = document.querySelector('link[href*="css/ionic.bundle.css"]');
+   const ionicThemeLinkTag = document.querySelector('link[href*="css/ionic/bundle.ionic.css"]');
+   if (!linkTag || ionicThemeLinkTag) {
+     return;
+   }
+   linkTag.setAttribute('href', linkTag.getAttribute('href').replace('ionic.bundle.css', 'ionic/bundle.ionic.css'));
+ }

window.Ionic = window.Ionic || {};
```

**Comment by BenOsodrac** [comment]
> Threading the [conversation](https://github.com/ionic-team/ionic-framework/pull/29791#issuecomment-2307400086) here:
> 
> @BenOsodrac I was able to confirm that switching from `<link href="../../../../../css/ionic.bundle.css" rel="stylesheet" />` to `<link href="../../../../../css/ionic/bundle.ionic.css" rel="stylesheet" />` does display the correct colors.
> 
> In order for the test pages and snapshots to display correct, let's also update the `core/scripts/testing/scripts.js`:
> 
> ```diff
>  // core/scripts/testing/scripts.js
> if (palette && palette[1] !== 'light') {
>   const linkTag = document.createElement('link');
>   linkTag.setAttribute('rel', 'stylesheet');
>   linkTag.setAttribute('type', 'text/css');
>   linkTag.setAttribute('href', `/css/palettes/${palette[1]}.always.css`);
>   document.head.appendChild(linkTag);
> }
> 
> + /**
> +  * The `ionic` theme uses a different stylesheet than the `iOs` and `md` themes.
> +  * This is to ensure that the `ionic` theme is loaded when the `ionic:theme=ionic`
> +  * and makes sure that the snapshot tests are rendered correctly.
> +  */
> + const theme = window.location.search.match(/ionic:theme=([a-z]+)/);
> + if (theme && theme[1] === 'ionic') {
> +   const linkTag = document.querySelector('link[href*="css/ionic.bundle.css"]');
> +   const ionicThemeLinkTag = document.querySelector('link[href*="css/ionic/bundle.ionic.css"]');
> +   if (!linkTag || ionicThemeLinkTag) {
> +     return;
> +   }
> +   linkTag.setAttribute('href', linkTag.getAttribute('href').replace('ionic.bundle.css', 'ionic/bundle.ionic.css'));
> + }
> 
> window.Ionic = window.Ionic || {};
> ```

Thanks for the code, already added it 👍. I'm facing some issues now with snapshots, trying to unblock it!

**Pull request merged**
