### PR TITLE
fix(item): matches material design character counter

### LINKED ISSUE #24334: bug: Material design implementation for counter display with ion-item
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The `counter` implementation with `ion-item` is incorrect with the Material Design Spec: https://material.io/components/text-fields.

### Expected Behavior

The counter should have the following changes:
- Text should be formatted with a space between the counts: `5 / 10` instead of `5/10` (related to #24327)
- Text color should be `rgba(0, 0, 0, .6)`
- Text letter spacing should be `0.0333333em`
- The counter should always push contents to appear right-aligned
- The counter should have `16px` of padding between itself and the contents to the left (in LTR)

### Steps to Reproduce

Have an item implementation using v6 with the counter feature:

```html
<ion-input [counter]="true">
   <ion-label position="stacked">Label</ion-label>
   <ion-input maxlength="20"></ion-input>
</ion-input>
```

Compare to the live example from the Material Design spec.

### Code Reproduction URL

https://codesandbox.io/s/prod-frog-eymwq?file=/src/app/app.component.html

### Ionic Info

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The counter implementation for `ion-item` has a few differences from the MD spec. Also the counter does not consistently display to the right of the container and can run into the helper/error text when long strings are used. 

Issue Number: Resolves #24334

## What is the new behavior?

- Updates text color for MD to `rgba(0, 0, 0, .6)`
- Updates letter spacing for MD to `0.0333333em`
- Updates left padding from counter to `16px`
- Updates counter string to match MD `5 / 10` instead of `5/10`
- Pushes counter to always display far right of the container

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Material Design specification can be found here: https://material.io/components/text-fields

### CODE REVIEW

**Review by amandaesmith3 — COMMENTED** [review]
These changes look good to me, but would the new shadow parts count as feature updates? 🤔 cc @liamdebeasi

**Comment by liamdebeasi** [comment]
Yeah this is a feature change, so it would go into the `feature-6.1` branch. Can we do a design doc before we merge so we can align on scope and requirements for this feature?

**Comment by sean-perkins** [comment]
Would it be worth splitting out those specific changes (and related issues) and keep this PR targeted on the visual issues with MD?

Happy to create a design doc on the shadow part changes and how they can be used/configured.

**Comment by liamdebeasi** [comment]
I think so. If we can limit this PR to the fixes noted in the linked issue and address the features for customization in a different PR, that would work with me.

**Review by amandaesmith3 — APPROVED** [review]
LGTM now 👍 Don't forget to update the PR description too.

**Pull request merged**
