### PR TITLE
feat(textarea): add counter and counterFormatter

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

It is not possible to specify a `counter` or `counterFormatter` on `ion-textarea`.

Issue URL: N/A

## What is the new behavior?

- Added support for showing maxlength counter text via `counter`.
- Added support for showing a custom formatter text via `counterFormatter`
- Added tests

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by amandaejohnston** [comment]
Looks like the PR description is copy-pasted from the other "bottom content" one? Don't forget to update that 👀

**Review by amandaejohnston — COMMENTED** [review]
A couple questions:
- There are some `bottom-content-error` and `bottom-content-helper` screenshots that appear to have snuck in here. Maybe the latest from the base branch needs to be merged in?
- Should we have a screenshot test for a counter alongside helper text? I believe `ion-input` had one that showed the input and full bottom content all together to make sure all the positioning was right.

**Comment by sean-perkins** [comment]
@amandaejohnston updated the PR description, looks like Github cached one of other open tabs when I submitted this one.

The screenshot additions are intentional here. The `.counter` container has an updated style for `letter-spacing`. This causes the error and helper text to render differently as a result of this PR. 

`ion-input` does not have screenshot captures for counter + helper/error from what I can tell. We render the containers in the test template, but do not have screenshot captures for them. I can update this PR to account for that.

**Comment by sean-perkins** [comment]
Ok this should be ready for another review. The textarea autogrow screenshots were apparently flaky, which resulted in the job adding a diff where the textarea was blank. I added a `page.waitForChanges()` to how that screenshot is captured, which now is capturing the screenshot consistently.

**Review by amandaejohnston — APPROVED** [review]

**Pull request merged**
