### PR TITLE
feat: allow noOutlet in Tab

### PR DESCRIPTION
**Pull request by riderx**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Each framework wrapper couples the ion-router-outlet within ion-tabs, prevent developers from using ion-tabs in a standalone context or passing in another router solution.

Issue URL:  https://github.com/ionic-team/ionic-framework/issues/25184

## What is the new behavior?

- Allow IonTab and IonTabbar to be use without any router

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

I didn't find where in the React wrapper this is implemented so I didn't make a change, for Angular i'm not sure about what to change

### CODE REVIEW

**Comment by sean-perkins** [comment]
Thanks for taking the initial discovery at this feature! 

To set up proper expectations on reviewing/merging; the team still needs to review my open feature request. Once the team agrees on the feature, we will internally create a design document that covers the necessary changes to each framework and discuss any possible issues with the suggested approach. Finally, the team would schedule the feature for a future release.

**Comment by riderx** [comment]
Thanks for the process info, could be interesting to have this process more public, to share and propose things!

**Comment by KANekT** [comment]
@sean-perkins do you have a plan to include this in release 6.2 ?

or should I not wait and make my own code ?

**Comment by sean-perkins** [comment]
@KANekT this feature will not be included in the 6.2 release. 

You are always able to maintain a fork of the code with your required changes in the interim. 

The Ionic team will still need to complete an internal feature design document for this feature before committing it to a feature release.

**Comment by amandaejohnston** [comment]
Thank you for the PR! We greatly appreciate the work you've put in, and the ability to use tabs without a router outlet is definitely something we're interested in adding to Ionic.

However, after talking this through with the team, we've decided it would be best to instead add this feature as part of an upcoming refactor we're making to the routing code that should simplify things greatly. This would allow us to add the feature to all three frameworks at once, rather than just Vue, and avoid any unnecessary extra work on anyone's part.

As such, I'm going to go ahead and close this PR out, but do let me know if you have any questions. Thank you again!

**Comment by riderx** [comment]
thanks @amandaejohnston for the insights.
where we can follow the work you doing in the routing ?
if there no public access to this i would have prefer to keep it open until release happen. otherwise it make us loose the track as community members.
if we keep it open or create public issue we could subscribe to the issue and know when that ready

**Comment by amandaejohnston** [comment]
The refactoring work will be mostly internal, but the original feature request for using tabs without a router outlet will remain open: https://github.com/ionic-team/ionic-framework/issues/25184 Updates on that front will be posted there as we have more to share.

**Comment by riderx** [comment]
thanks !

**Pull request closed without merging**
