### PR TITLE
docs(platform): add capacitor to method docs

### LINKED ISSUE #23687: bug: @ionic/angular - platform.is() is missing 'capacitor' in method documentation
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

```
  /**
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | cordova         | on a device running Cordova.       |
   * | ios             | on a device running iOS.           |
   * ....
   *
   */
  is(platformName: Platforms): boolean {
    return isPlatform(this.win, platformName);
  }
```

The string 'capacitor' existing as a platform and in the type definition of `Platforms` but it is missing in the method documentation. 

### Expected Behavior

```
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | capacitor       | on a device running Capacitor.     |
   * | cordova         | on a device running Cordova.       |
   * | ios             | on a device running iOS.           |
   * ...
   *
   */
  is(platformName: Platforms): boolean {
    return isPlatform(this.win, platformName);
  }
```

The string 'capacitor' is added to the method documentation. 

### Steps to Reproduce

Check the method documentation of `@ionic/angular` v5.6.12.

### Code Reproduction URL

_No response_

### Ionic Info

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by meck93**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
fixes #23687

Issue Number: #23687

## What is the new behavior?

- method documentation updated

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by liamdebeasi — APPROVED** [review]
Thank you! This is good to merge when tests pass. Just as a heads up, the `capacitor` option is documented on our docs website here: https://ionicframework.com/docs/angular/platform#methods. We recommend going there for the most up to date API information.

**Comment by meck93** [comment]
> Thank you! This is good to merge when tests pass. Just as a heads up, the `capacitor` option is documented on our docs website here: https://ionicframework.com/docs/angular/platform#methods. We recommend going there for the most up to date API information.

No worries @liamdebeasi - I realized that the TypeScript definition and website were correct but thought I still might update the method documentation as we noticed this issue this morning internally. Or do you rather want to remove the complete method documentation?

**Comment by liamdebeasi** [comment]
We can still merge this. I think it will be useful for anyone working inside of the code there.

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
