### PR TITLE
fix(loading): spinner now respects —spinner-color

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25180

## What is the new behavior?

- All spinners now have the correct color set when using inside of ion-loading

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Note: Rather than add another test for this specific usage, I updated the existing test to account for this new behavior.

### CODE REVIEW

**Review by amandaejohnston — COMMENTED** [review]
Would it be possible to add a timeout or something so the loading spinner is more visible in the screenshots? I worry that if this does regress in the future, it'll be hard to tell what's going on. 🤔 

Also, one of the popover screenshots got updated and the popover is now missing; looks like that test might be flaky?

**Comment by liamdebeasi** [comment]
re: popover screenshots: that looks like FW-1397. Let me take a look and see if I can fix it.

**Comment by liamdebeasi** [comment]
Ok I did a couple things:

1. Opened https://github.com/ionic-team/ionic-framework/pull/25267 which should correctly skip the picker internal test on WebKit. Will sync those changes into this branch when I merge the PR.
2. Updated the loading test to use `lines-sharp`. This is another one of the affected spinners but has more content rendered in the initial paused state.

**Comment by amandaejohnston** [comment]
Much better, thanks!

**Review by amandaejohnston — APPROVED** [review]

**Pull request merged**
