### PR TITLE
chore(github-actions): use flexible options to update screenshots

### PR DESCRIPTION
**Pull request by thetaPC**
Issue number: N/A

---------

## What is the current behavior?

GitHub actions allow screenshots to be updated either by updating all the components or providing a component name.

If a component name is given, then the screenshots will only be updated on `src/components/{component-name}`. This isn't ideal when wanting to update a specific path.

## What is the new behavior?

- The script no longer strips out `ion-`. The developer needs to submit a valid component name or valid path.
- The script no longer appends the value to `src/components/`
- The script will run all instances of a component if only the name is given
- The script will run tests within a given path

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

How to test:

1. Create a new branch based off this one
2. Make a style change
3. Push it to the new branch
4. Update the reference images using the new branch
5. This will show you all the options

Recommended to test:
- a component name (`chip`)
- a path (`src/components/chip/test/a11y`)
- a component that doesn't exist (`random-component`)
- no provided component, leave the first input blank

### CODE REVIEW

**Review by brandyscarney — CHANGES_REQUESTED** [review]
I ran the update screenshots action with the following inputs:

- ✅ [`badge`](https://github.com/ionic-team/ionic-framework/actions/runs/7933365142/job/21662032257) - Runs: `npx playwright test src/components/badge`
- ❌ [`src/components/badge/test/basic`](https://github.com/ionic-team/ionic-framework/actions/runs/7933368514/job/21662037071) - Runs: `npx playwright test src/components/src/components/badge/test/basic`
- ✅ [`badge tabs`](https://github.com/ionic-team/ionic-framework/actions/runs/7933371218/job/21662046716) - Runs: `npx playwright test src/components/badge src/components/tabs`
- ✅ [`unknown`](https://github.com/ionic-team/ionic-framework/actions/runs/7933371218/job/21662046716) - Runs: `npx playwright test src/components/unknown`
- ✅ [blank](https://github.com/ionic-team/ionic-framework/actions/runs/7933381841/job/21662088633) - Runs: `npx playwright test`

The only one that didn't work as expected is the 2nd one. It appended the entire path onto `src/components`.

**Review by brandyscarney — APPROVED** [review]
Running the update screenshots action with latest results in the following:

- :white_check_mark: [`badge`](https://github.com/ionic-team/ionic-framework/actions/runs/8334144829) - Runs: `npx playwright test badge`
- :white_check_mark: [`src/components/badge/test/basic`](https://github.com/ionic-team/ionic-framework/actions/runs/8334150308) - Runs: `npx playwright test src/components/badge/test/basic`
- :white_check_mark: [`badge tabs`](https://github.com/ionic-team/ionic-framework/actions/runs/8334155107) - Runs: `npx playwright test badge tabs`
- :white_check_mark: [`unknown`](https://github.com/ionic-team/ionic-framework/actions/runs/8334157237) - Runs: `npx playwright test unknown`
- :white_check_mark: [blank](https://github.com/ionic-team/ionic-framework/actions/runs/8334161154) - Runs: `npx playwright test`

Looks good to me! :+1: Let me know if you need me to test it after the Docker update is merged in, but I don't think it should be affected.

**Comment by thetaPC** [comment]
@brandyscarney just to be safe, let's test it with the docker changes.

**Review by brandyscarney — APPROVED** [review]
Still works with Docker 👍

**Pull request merged**
