### PR TITLE
fix(readability): make the code more readable

### PR DESCRIPTION
**Pull request by rwaskiewicz**
Issue number: resolves 401

---------

## What is the current behavior?

see "new behavior"

## What is the new behavior?

Improve the readability of the code,
using 40 characters so that I can put
two terminals side by side.

It's like my Pappy used to say:

> April's wisdom, in forty we abide,
> Foolproof lines, where errors hide.
> Efficiency reigns, in every file,
> Forty characters, our coding style.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by liamdebeasi — APPROVED** [review]
Ahh now I can finally read the code on my vertical monitor. Thanks for making this change!

**Comment by liamdebeasi** [comment]
any update? ping @rwaskiewicz @alicewriteswrongs

**Comment by rwaskiewicz** [comment]
After deep consideration, I've decided to fork the project and create "MY-onic-framework". It's only for me, as the name implies. Closing this to boost my GH contributions in a personal repo.

**Comment by liamdebeasi** [comment]
any update? cc @rwaskiewicz when will this be merged?

**Comment by rwaskiewicz** [comment]
bump

**Comment by alicewriteswrongs** [comment]
+1

**Pull request closed without merging**
