### PR TITLE
feat(input): add color prop support

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Developers using the new input syntax do not have a way of using the Ionic theme to apply a particular theme to `ion-input`.

## What is the new behavior?

- Add support for using the `color` prop as per the design document

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sean-perkins — COMMENTED** [review]
A few screenshot captures have the label cropped, e.g.:
- core/src/components/input/test/color/input.e2e.ts-snapshots/input-outline-color-floating-md-ltr-Mobile-Chrome-linux.png
- core/src/components/input/test/color/input.e2e.ts-snapshots/input-outline-color-floating-md-ltr-Mobile-Firefox-linux.png
- core/src/components/input/test/color/input.e2e.ts-snapshots/input-outline-color-floating-md-ltr-Mobile-Safari-linux.png
- core/src/components/input/test/color/input.e2e.ts-snapshots/input-outline-color-stacked-md-ltr-Mobile-Chrome-linux.png

This is likely because the input bounding box does not contain the translated label for these displays.

**Comment by amandaejohnston** [comment]
I'm not seeing the colors when running the test locally on Chrome ([screenshot](https://i.gyazo.com/9db6208225e842c0e639741d945ab575.png)), should I be?

**Comment by liamdebeasi** [comment]
The colors only apply when focusing the input as per the MD spec: https://m2.material.io/components/text-fields

**Comment by liamdebeasi** [comment]
@sean-perkins Do you want me to add top padding to the MD screenshots? I'm not sure how much additional information we would gain by adding it though.

**Review by amandaejohnston — APPROVED** [review]

**Comment by sean-perkins** [comment]
I think we are good as-is, as long as the screenshot capture is consistent. We can re-evaluate in the future if it becomes a problem.

**Pull request merged**
