### PR TITLE
fix(vue): cache attached view reference

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Developers using Vue can run into an error when using an `ion-select` that presents a popover of options. The Vue delegate was incorrectly assuming that a component instance would always be passed as the argument to `attachViewToDom`.

This is not the case for `ion-select`, where a string of the tag name is used: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/select/select.tsx#L414

Issue URL: https://github.com/ionic-team/ionic-framework/issues/26643#issuecomment-1406611223
resolves https://github.com/ionic-team/ionic-framework/issues/26695

## What is the new behavior?

- Caches the reference to the created element, so the `WeakMap` always receives an object to that can be used for looking up and unmounting an overlay.
- Refactored the property to better signal that it can be an "object" (`any`) or a string. Note: Because any will overwrite the types, this does nothing from a typings perspective. This is just a visual signal to a developer. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Repro: https://github.com/acoldfox/ionic-select-issue (you will need to install the dev-build to verify)

Dev-build: `6.5.2-dev.11674852369.1c9fe737`

### CODE REVIEW

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
We need a test for this. Also why does this issue not impact Ionic React?

**Comment by liamdebeasi** [comment]
Also be sure to note that this fixes https://github.com/ionic-team/ionic-framework/issues/26695 when merging

**Review by liamdebeasi — APPROVED** [review]
Good to go once we have a test. Thanks for taking care of this!

**Comment by sean-perkins** [comment]
Ok - test case has been added.

Also confirmed against the original root issue: https://github.com/raymer/ionic-modal-bug that the expected behavior still occurs after this change.

**Pull request merged**
