### PR TITLE
feat(alert): support dynamic font scaling

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: N/A

---------

## What is the current behavior?

Alert does not support Dynamic Font Scaling

## What is the new behavior?

- Alert supports Dynamic Font Scaling

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by thetaPC** [comment]
I just merged in the changes for the checkbox icon. Please pull those changes and update the screenshots.

**Review by thetaPC — CHANGES_REQUESTED** [review]
The max-width also changes when scaling. These screenshots are from the Health app on iOS.

| 310% | 100% |
|--------|--------|
| Simulator Screenshot - iPhone 14 Pro - 2023-09-28 at 09 44 56 | Simulator Screenshot - iPhone 14 Pro - 2023-09-28 at 09 45 17 |

**Comment by liamdebeasi** [comment]
Great catch! I fixed this in https://github.com/ionic-team/ionic-framework/pull/28236/commits/0f807c323d04937eb50b21a56d64577a8078c294

**Comment by thetaPC** [comment]
Can you check if Android scales the width as well? I tried building a native app but keep running into issues.

**Comment by liamdebeasi** [comment]
Good question! The alerts don't seem to scale horizontally:

| Default | Max Scale |
| - | - |
| Screenshot_20230929-133801 | Screenshot_20230929-133831 |

**Review by thetaPC — APPROVED** [review]
LGTM

**Pull request merged**
