### PR TITLE
fix(toolbar): MD height only applies to MD segment

### PR DESCRIPTION
**Pull request by liamdebeasi**
⚠️ Give co-author credit to Brandy when merging.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/18617

This relevant only applies to the MD toolbar, but it expects that the slotted segment is also running in MD mode. When using the segment in iOS mode, the min height is applied too.

This fix was done to align with the MD spec for segments in a toolbar: https://github.com/ionic-team/ionic-framework/pull/17537

## What is the new behavior?

- The min-height now only applied to MD segments.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Could we just apply `min-height` to all slotted `ion-segment` in `toolbar.scss` and set the `ios` one to something like `auto`?

**Comment by liamdebeasi** [comment]
What's the benefit of doing it that way?

**Comment by brandyscarney** [comment]
That way we don't have a CSS variable that only works in `md` mode.

**Comment by liamdebeasi** [comment]
The `--min-height` CSS Variable already works in both iOS and MD mode, so this PR does not change that functionality. See https://github.com/ionic-team/ionic-framework/blob/b43f17fc4af1c79ea340204e26ef31598092cacf/core/src/components/toolbar/toolbar.scss#L69

**Review by amandaejohnston — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Brandy proposed an alternative offline that I adapted. Updated the implementation and added a test.

**Review by amandaejohnston — APPROVED** [review]

**Review by brandyscarney — APPROVED** [review]
This looks good. Should we add a screenshot that shows it inheriting the md height though?

**Comment by liamdebeasi** [comment]
We have screenshots for the inheritance already (example: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/segment/test/toolbar/segment.e2e.ts-snapshots/segment-toolbar-md-rtl-Mobile-Safari-linux.png)

**Comment by brandyscarney** [comment]
@liamdebeasi Sorry I meant one where we set `--min-height` on toolbar to another value and verify it only changes the md one, but if you think that one is enough then this is fine with me.

**Comment by liamdebeasi** [comment]
Yeah I think the current screenshot should be fine since it has `--min-height` explicitly set to `56px`. I'm not sure that having a screenshot where `--min-height: 40px` or something would show us anything new.

**Pull request merged**
