### PR TITLE
fix(ion-virtual-scroll): class spacing

### PR DESCRIPTION
**Pull request by positlabs**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

Honestly, I didn't do any of the above. It's a few spaces...

## Pull request type

Please check the type of change your PR introduces:
- [ x ] Bugfix

## What is the current behavior?

Class names are appended without spaces, e.g. `'myclassvirtual-item '` or `'myclassvirtual-loading'`

## What is the new behavior?

- class names are properly separated

## Does this introduce a breaking change?

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! How can I reproduce this? If I add the class to the virtualItem, like the following:

```html
<ion-item *virtualItem="let item" class="my-item">
```

I am able to see the classes being added with spaces, both inspecting and logging `classList`:

Screen Shot 2019-07-24 at 4 01 26 PM
Screen Shot 2019-07-24 at 4 01 35 PM

**Comment by positlabs** [comment]
It might just be an issue in vanilla html. I was trying to use it in a Stencil app

**Comment by liamdebeasi** [comment]
Hey there, 

Is this still an issue? If so, can you please provide a repo we can use to reproduce the issue?

**Comment by positlabs** [comment]
Ah, it's been so long... But if you can just take a look the commit you can see the issue pretty clearly. If you don't have the space initially, then it will concatenate the string directly onto the existing classes (e.g. "myclassvirtual-item") instead of spacing them out (e.g. "myclass virtual-item")

Screen Shot 2020-11-11 at 12 13 13 PM

**Comment by amandaesmith3** [comment]
Thanks for the PR, we appreciate your work!

I discussed this internally with the team, and we decided to close this PR out. In the time that's passed, `ion-virtual-scroll` has since been [deprecated](https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#570-potassium-2021-09-01), so we've decided not to move forward with this change.

For future PRs, you can help us triage quickly by including a reproduction of the bug you're fixing, and/or linking to a related Github issue. Thank you!

**Pull request closed without merging**
