### PR TITLE
fix(picker-column): detect pressed

### PR DESCRIPTION
**Pull request by devinova**
## Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Feature
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
The picker's pull movement incorrectly calculates the drag speed. After dragging the mouse or finger, after holding down and stopping, the picker does not take the stop into account and calculates de speed incorrectly.

Issue Number: #23034

## What is the new behavior?
After dragging the mouse or finger, after holding down and stopping, the picker must take the stop into account and calculate a lower drag speed

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devinova** [comment]
can someone give me feedback on this fix?

**Comment by devinova** [comment]
could someone give me feedback on a correction?

**Comment by mhartington** [comment]
we will review this when we have time. You do not need to tag people.

**Comment by amandaesmith3** [comment]
Thanks for the PR! We greatly appreciate your work. The team and I have discussed this internally. We've found that the issue this addresses is still a problem in the latest version of Ionic, and is one we're still interested in fixing. Due to the age of this PR, we've decided to open a new PR that uses these code changes, updating them for the latest codebase as necessary, and give you co-author credit to ensure you're properly recognized. I'm going to close this one out, but you can expect the new one soon. Thanks again!

**Pull request closed without merging**
