### PR TITLE
feat(vue): add optional IonicConfig type parameter to IonicVue plugin

### PR DESCRIPTION
**Pull request by Sukaato**
Issue number: https://github.com/ionic-team/ionic-framework/issues/29659

---------

## What is the current behavior?

while using `.use(IonicVue, {})`, the config object has no autocomplete.

## What is the new behavior?

- Add type autocomplete on plugin option in VueJS package.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Sukaato** [comment]
Any update on this PR ?

**Comment by thetaPC** [comment]
@Sukaato Thank you for the PR!

Is this PR associated to an open issue? If it is, please add the issue number. If it's not, please open a new issue that highlights the reason why this PR is needed.

**Comment by Sukaato** [comment]
here's the issue: https://github.com/ionic-team/ionic-framework/issues/29659

**Comment by reslear** [comment]
everyone would stop using :)
`// @ts-ignore`

**Review by thetaPC — APPROVED** [review]
LGTM

**Pull request merged**
