### PR TITLE
feat(spinner): updated styles for latest iOS

### PR DESCRIPTION
**Pull request by EinfachHans**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Update the *ion-spinner* `lines` & `lines-small` to match latest iOS changes

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22782

## What is the new behavior?

- 8 lines instead of 12
- `fn()` adjusted to work with `total`
- stroke-width increased

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR. If we are going to ship this as the new default, we are going to need to revise how `ion-refresher` works too. Two things stick out in that regard:

1. The default spinner color is gray instead of dark gray/black in pull to refresh on native iOS (see Mail app)
2. The tick marks all progressively fade in rather than appear as you pull.

@brandyscarney I do think we need this change for the iOS 14 design revisions, but do you think this should be the new default or a separate option?

**Comment by EinfachHans** [comment]
@liamdebeasi i also created this PR: #22398 - i think the changes you mentioned should be done there?

**Comment by EinfachHans** [comment]
@liamdebeasi i did the both changes that u mentioned in the refresher PR #22398 😊 

In combination with this PR here, if u merge both together, the native Pull-To-Refresh will look like this (slowed down):

**Comment by rgoldiez** [comment]
@liamdebeasi - what the process to get this PR and https://github.com/ionic-team/ionic-framework/pull/22398 reviewed and merged?

**Comment by EinfachHans** [comment]
@rgoldiez as far as i know are ios14 design changes planned for Version 6

**Comment by liamdebeasi** [comment]
I made a few changes to your PR, but I think this is ready to merge. The biggest change is we added back the old spinner style under the `lines-sharp` and `lines-sharp-small` values for those who prefer the less iOS-like spinner style.

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
