### PR TITLE
fix(progress-bar): use correct theme colors

### LINKED ISSUE #20098: bug: Progress bar doesn't use theme colors
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Using an `ion-progress-bar` with a dark theme results in a white progress bar.

**Expected behavior:**

Progress bar would pick up the theme colors.

**Steps to reproduce:**

1. Create an app with a progress bar
2. Use the dark theme
3. Progress bar is a white strip

**Related code:**
I had to do the following to fix it:
```css
ion-progress-bar {
  --buffer-background: var(--ion-background-color);
  --background: var(--ion-background-color);
  --progress-background: var(--ion-color-step-400);
}
```

It seems like that should be the default.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.12 
   Ionic Framework : @ionic/react 4.11.6

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.0 
   npm    : 6.13.4
   OS     : macOS Mojave
```

### PR DESCRIPTION
**Pull request by liamdebeasi**
TODO: Give co-author credit to domske

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #20098

## What is the new behavior?

- Don't place a white background on the buffer bar to allow theming to work properly

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

| Before | After |
| ---| ---|
| before | after |

### CODE REVIEW

**Comment by brandyscarney** [comment]
The dots appear pretty visibly on the regular buffer bar (but not reversed):

**Review by brandyscarney — APPROVED** [review]

**Comment by domske** [comment]
Hmm, something went wrong. In my original commit, the dots are moved synchron with the progress bar. And the dots container was overflow hidden. So that the dots are smoothly appear and disappear on the edges. But with the current state it looks like this (The dots shines through. And are not animated sync.)

demo

Brandy, your GIF: is that an optical illusion or are the dots going in the wrong direction?

**Comment by liamdebeasi** [comment]
Thanks, I forgot a transition. I will resolve that here: https://github.com/ionic-team/ionic-framework/pull/22964

Because we are animating `transform` and `width`, they won't be perfectly in sync, but the overlap/gap should not be nearly as noticeable after my PR.

For the dots disappearing, that has always been there. The issue is just more pronounced because the dots no longer go behind the buffer. One idea is to animate background position rather than transform, but there may be some performance issues associated with that.

**Comment by domske** [comment]
Ok, but if the wrapper is overflow hidden, the dots will also not behind the buffer. (as in my original commit). 
demo
<sub>(This is from Vuetify, not from Ionic)</sub>

But I not yet viewed my orginal and the current state of the source code.  So please don't get confused by me. ^^

**Comment by domske** [comment]
btw. the live reload does not update changes in scss. I have to restart on every change by `npm start`. Changes in jsx works. Is there a trick?

**Comment by brandyscarney** [comment]
@domske Yes we run into similar issues with the stencil build, I believe it is this issue https://github.com/ionic-team/stencil/issues/2635

As a workaround if you make a change in `progress-bar.scss` you can update `progress-bar.ios.scss` to trigger the style changes.

**Comment by domske** [comment]
@brandyscarney Thanks, It works. But updating the `.(ios|md).scss` collapses the styles of the site and I have to press the refresh button of the browser. So both solutions *sigh* anyway ...

**Comment by domske** [comment]
Back to the issue: Don't set width / height on e.g. 100% when using left/right/top/bottom. It's a style conflict / overwrite. 
Example: 

```scss
left: -10px;
right: -10px;
width: 100%;
```
will not work. The element is now left: -10px and width 100% instead of 100% + 20px.

**Comment by liamdebeasi** [comment]
I wonder if it makes sense to keep the container that was in the old PR, set `overflow: hidden` and just change the width of that container. It might make for a nicer effect.

The reason why we changed the PR was because it was animating `left` which has some performance implications. I'll see if there's a better way to do this later this week.

**Comment by domske** [comment]
The only idea with the overflow-hidden container, is that the dots can move behind the progress bar without shining through.
So, without this container - and only change the width, results in a aprupt disapearing dot background. Because you cannot move some pixels forward without overlay the progress bar. ...
I test some other solution (simpler) at this moment. But it's a bit tricky this little component. ^^
Where do you benchmark the style performance? I know that transform and other 3d accelerated stuff is better. Aber is there a way to measure things like `left` vs `translateX` or `scaleX` vs `width`, etc?

**Comment by liamdebeasi** [comment]
Yeah, I like that overflow hidden container idea.


Re: benchmarking style performance-- this is a shameless plug but I go over the tools I use here: https://www.youtube.com/watch?v=A5a15NrcGoM

Using `left` probably isn't the end of the world performance-wise but we prefer to stick with `transform` where possible.

**Comment by domske** [comment]
So fixed #22965 😓 But feel free to modify.

**Comment by liamdebeasi** [comment]
Thank you! I will take a look at the PR.

**Pull request merged**
