### PR TITLE
force web attribute for ios/android

### PR DESCRIPTION
**Pull request by aboalwi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): 
Having more options.

## What is the current behavior?
It's automatically decide to use native or web refresher based on pre-defined conditions.

Issue Number: N/A

## What is the new behavior?
Can always use web ion-refresher by using forceWebIos/forceWebAndroid attributes.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Having ios scrolling issues because of bounce so we basically disabled bounce completely in ios. This caused ion-refresher to stop working this will help us keep going with our project.

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR. What problem does this PR solve? The refresher should automatically detect which variant to use based upon the mode of your application.

**Comment by aboalwi** [comment]
The problem is ion-refresher native implementation never works on iOS when bounce/rubber band is disabled. This forces ion-refresher to use the web implementation instead. 
I had to disable iOS bounce for scroll issues like: When a video is playing inside a list and user scroll to top or bottom. Or an ion-range is being dragged and scroll to top.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. The native iOS implementation relies on the rubber band effect to work, but there's an easier way to accomplish what you are trying to do.

Setting the `pulling-icon` property on `ion-refresher-content` to an arrow icon (see https://ionicons.com/ for options) will force the refresher to use the web implementation instead on iOS mode. For example, you could do something like this:

```html
<ion-refresher>
  <!-- this would be `pullingIcon="arrow-down"` instead in Ionic Angular -->
  <ion-refresher-content pulling-icon="arrow-down"></ion-refresher-content>
</ion-refresher>
```

Can you give that a try and let me know if it resolves the issue?

**Comment by aboalwi** [comment]
Yep it works! Thanks!

**Pull request closed without merging**
