### PR TITLE
test(config): update to playwright 1.29.0

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Our playwright installation is on an old version.

## What is the new behavior?

- Updated Playwright to v1.29.0
- Re-enabled the translucent screenshots tests on Firefox. Playwright 1.29.0 ships with Firefox v107 which has support for `backdrop-filter`: https://github.com/microsoft/playwright/releases https://caniuse.com/?search=backdrop-filter. We are currently on v100.
- Disabled certain tests that call `focus()` in Safari (see item 3 below)
- Updated the form data test to account for cross browser differences.
- Adjusted whitespace in certain tests to account for https://bugs.webkit.org/show_bug.cgi?id=247081
- Skipped a datetime-button render test on Firefox because it is now flaky.

As part of this upgrade, Ionic team members need to be aware of the following changes:

1. `toHaveText` now pierces open shadow roots. As a result, the datetime tests were reading the `<title>` in `ion-icon` for the month/year picker toggle. This should not impact us anymore once https://github.com/ionic-team/ionicons/issues/838 is resolved. Team members can do `toHaveText(/April 2022/)` to work around this for now.
2. `toHaveAttribute(NAME, '')` no longer matches elements that lack `NAME`. Instead, we will need to get the value of `Locator.getAttribute()`.
3. Manually moving focus in Safari 16 on macOS will no longer work due to new focus preferences. By default, focusing only highlights text fields and pop-up menus. This can be changed in "Advanced" to highlight each item (including non text field/pop up elements), but we do not have access to this configuration in Playwright. As a result, features in Ionic that manually call `.focus()` likely will not work unless the feature in "Advanced" is turned on. This does not impact `page.keyboard.press('Tab')` as you can continue to do `page.keyboard.press('Alt+Tab')`. Team members should manually verify focus management fixes on a physical iOS device.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Blocked on https://github.com/ionic-team/ionic-framework/pull/26405. I will return to this in the future.

**Review by amandaejohnston — COMMENTED** [review]
I noticed the translucent effect is gone from the header in the updated screenshot here: `core/src/components/popover/test/basic/popover.e2e.ts-snapshots/popover-basic-translucent-header-popover-ios-rtl-Mobile-Safari-linux.png`

**Comment by liamdebeasi** [comment]
Thanks! I'm going to move this back to a draft until I can figure out why this is happening.

**Comment by liamdebeasi** [comment]
Ok I was able to clean up the remaining screenshot diffs. I also updated to Playwright 1.29.0.

**Review by sean-perkins — APPROVED** [review]
Looks good to me. 

We should consider removing `ion-datetime` from the `ion-item`/inputs tests in the future.

e.g.: core/src/components/item/test/inputs/item.e2e.ts-snapshots/item-inputs-disabled-md-rtl-Mobile-Safari-linux.png

**Review by amandaejohnston — COMMENTED** [review]
Looks like the translucency issue might still be present; the header looks different in these screenshots:
- `core/src/components/popover/test/basic/popover.e2e.ts-snapshots/popover-basic-translucent-header-popover-ios-ltr-Mobile-Safari-linux.png`
- `core/src/components/popover/test/basic/popover.e2e.ts-snapshots/popover-basic-translucent-header-popover-ios-rtl-Mobile-Safari-linux.png`

**Comment by liamdebeasi** [comment]
The translucency behavior isn't working for me locally either, so I think this may be an intentional change. Perhaps Safari changed some behavior that caused our workaround to no longer work?

**Review by amandaejohnston — APPROVED** [review]
Hm, probably okay in that case, though we may want to make a ticket to look into that separately.

**Pull request merged**
