### PR TITLE
fix(ion-alert) when display iOS keyboard, fix alert display position.

### PR DESCRIPTION
**Pull request by rdlabo**
#### Short description of what this resolves:
When use iOS with Cordova or Capacitor, keyboard display resize with `ion-app` . But if `position: fixed`, ion-alert will not fix the position. If these setting.

```Cordova
<preference name="KeyboardResizeMode" value="ionic" />
```

```Capacitor
{
  "plugins": {
    "Keyboard": {
      "resize": "ionic",
    }
  }
}
```

スクリーンショット 2019-03-14 1 43 37

#### Changes proposed in this pull request:

- When use iOS with Cordova or Capacitor,  ion-alert is `position: absolute;`

スクリーンショット 2019-03-14 1 43 47

**Ionic Version**: 4.2

**Fixes**: #

### CODE REVIEW

**Comment by pwespi** [comment]
Thank you for this PR. I have been fighting with this issue for some time and can confirm that setting the position to absolute works.

**Comment by brandyscarney** [comment]
Thank you for the PR! I can only reproduce this with the keyboard plugin installed so I think this needs more investigation into whether it's a core issue or issue with the plugin.

**Comment by rdlabo** [comment]
@brandyscarney Thanks for review. It seems ion-alert height is not `ion-app` or `app-root` .  `ion-alert` height is `body` height in iOS app... This is Safari's specification. 

スクリーンショット 2019-04-25 11 26 40

Thanks.

**Comment by ippeiukai** [comment]
> I can only reproduce this with the keyboard plugin installed so I think this needs more investigation into whether it's a core issue or issue with the plugin.

@rdlabo @brandyscarney I think keyboard plugin having KeyboardResizeMode value `native` (default), ion-alert behaves fine because the entire viewpoint gets smaller with keyboard open; the alert moves to the middle of now smaller viewport. When KeyboardResizeMode is `body` or `ionic` however, the viewport height stays at full device height and the height of the `body` or `ion-app` gets smaller instead; the alert stays at middle of the screen partially underneath the keyboard.

I've stumbled on this bug while experimenting with `<preference name="KeyboardResizeMode" value="ionic" />` with `<plugin name="cordova-plugin-ionic-keyboard" spec="2.1.3" />`.

**Comment by ippeiukai** [comment]
I ended up with following lines in `theme/variables.scss` for now; seems to work but not sure how safe it is:

```SCSS
.ios {
  ion-alert {
     // HACK: https://github.com/ionic-team/ionic/pull/17776
     position: absolute !important;
   }
}
```

**Comment by Stylemayster** [comment]
I have this issue too. @ippeiukai your fix is interresting, but doesn't seem to work. You are with ios 12?

**Comment by EinfachHans** [comment]
Using @ippeiukai 's workaround works for me. Pls investigate into this

**Comment by liamdebeasi** [comment]
Hi everyone,

Two things I want to mention:

1. I need to make some changes to this PR, but I do not have access to the branch. I am going to close this PR in favor of https://github.com/ionic-team/ionic-framework/pull/22425, but I will give @rdlabo co-author credit when merging the PR.
2. Can everyone try this dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@5.5.0-dev.202011031551.413950b
```

**React**
```
npm install @ionic/react@5.5.0-dev.202011031551.413950b @ionic/react-router@5.5.0-dev.202011031551.413950b
```

**Vue**
```
npm install @ionic/vue@5.5.0-dev.202011031551.413950b @ionic/vue-router@5.5.0-dev.202011031551.413950b
```

**Vanilla JS**
```
npm install @ionic/core@5.5.0-dev.202011031551.413950b
```

**Comment by EinfachHans** [comment]
@liamdebeasi tested - works for me 😊

**Comment by liamdebeasi** [comment]
Hi everyone, this has been merged in https://github.com/ionic-team/ionic-framework/pull/22425 and a fix will be available in an upcoming release of Ionic Framework.

**Comment by rdlabo** [comment]
Hi. I'm glad to fix this, and I could contribute. Thanks @liamdebeasi

**Pull request closed without merging**
