### PR TITLE
fix(router): matchIDs now correctly accounts for all parameters

### LINKED ISSUE #24641: bug: probable bug in #24315
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The fix in #24315 improves the router behavior by comparing the parameters on top of the ID which makes matchesIDs more robust.

I think that a few things could be improved in this CL:

https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router/utils/matching.ts#L72-L80

The code assume that all segments of the chain ((`routeChain.path[j]`)) are parameter segment of the form (`/:param`). It doesn't account for fixed segments.

https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router/utils/matching.ts#L72-L80

The code also assumes that all `routeIdParams` are populated from the parameter segments (i.e. `:params`). It misses the case where the parameters are populated from the `componentProps` of the `<ion-route>`.

If we agree on the those 2 points, I'd like to propose a PR.

@sean-perkins, what do you think ?

### Expected Behavior

Take into account fixed segments and componentProps.

### Steps to Reproduce

I modified the tests locally to make sure those 2 cases are not taken into account.

### Code Reproduction URL

_No response_

### Ionic Info

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by vicb**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: fixes #24641

## What is the new behavior?

`<ion-route>` parameters and fixed segments are taken into account when matching IDs.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by vicb** [comment]
@sean-perkins I added an e2e and more unit tests in this PR. It should be ready to go once #24627 is in (pending  review of course)

**Comment by vicb** [comment]
@sean-perkins is there anything missing from this PR ? (merging it would allow sending me follow up PRs with more fixes to the router).
Thanks !

**Comment by vicb** [comment]
ping ? _(it has been 3 weeks)_

**Review by sean-perkins — APPROVED** [review]

**Comment by vicb** [comment]
(and sorry for being impatient but I have already 5 PRs ready to get and probably another 5 for further fixes and features)

**Review by amandaesmith3 — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Thanks for the PR! We appreciate all the work you put into creating this. After discussing with the team, we have decided not to accept this PR.

We would prefer to solve this issue in alternative ways by encouraging developers to access `ion-router` to use routing instead of `ion-nav`. We feel that the approach this PR takes would make future changes to how `ion-router` works difficult to build. I understand that this change will likely take longer than this fix did to build, but we feel that it is what is best for the vanilla JS router long term.

I am going to close this PR. Thank you!

**Pull request closed without merging**
