### PR TITLE
Add keep-alive functionality

### PR DESCRIPTION
**Pull request by michaeltintiuc**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
There is no way to cache components using `ion-vue-router` due limitations imposed by [Vue API](https://vuejs.org/v2/api/#keep-alive) which state that `keep-alive` should be a direct child of `transition` when used together.

Issue Number: N/A

## What is the new behavior?
Allows usage of `keep-alive` as a property of `ion-vue-router`

Basic usage:

`<ion-vue-router keep-alive />`

Equates to:
```vuejs
<keep-alive>
  <router-view />
</keep-alive>
```

Passing props:
`<ion-vue-router :keep-alive="{ include: 'SomeComponent' }" />`

Equates to:
```vuejs
<keep-alive include="SomeComponent">
  <router-view />
</keep-alive>
```

Same as the original API you can pass `string`, `string[]` or `RegExp` to `include` and `exclude` properties.

RegExp:
`<ion-vue-router :keep-alive="{ include: /Some/ }" />`

Equates to:
```vuejs
<keep-alive :include="/Some/">
  <router-view />
</keep-alive>
```

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Livijn** [comment]
This would be very good!

**Comment by Livijn** [comment]
@mhartington Lets merge this, shall we?

**Comment by guilhermeagirardi** [comment]
Is this implementation already working?

**Comment by michaeltintiuc** [comment]
@guilhermeagirardi would appreciate you testing this feature here https://github.com/ModusCreateOrg/ionic-vue if building from source is a problem. Consider this PR an RFC, any feedback is highly valuable

**Comment by liamdebeasi** [comment]
Thanks for the PR! I am going to close this as this is for the old Ionic Vue code base.

**Pull request closed without merging**
