### PR TITLE
fix(angular): setting props on a signal works

### LINKED ISSUE #28876: bug: componentProps of modalController does not work with Angular 17.1.0 signal inputs
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Passing componentProps (when using a modalController) throws an error when the input of the component is a signal (Input signals are a feature of Angular 17.1.0).

### Expected Behavior

The componentProps should work even if the component input is a signal.

### Steps to Reproduce

1. Create a component to pass to a modalController which has signal inputs.
2. Create a modal controller with componentProps that correspond to the component's input signals.
3. Open the modal and observe the results with dismay.

### Code Reproduction URL

https://github.com/ntorrey/ionbug

### Ionic Info

Ionic:
   Ionic CLI                     : 7.2.0 
   Ionic Framework               : @ionic/angular 7.6.6
   @angular-devkit/build-angular : 17.1.1
   @angular-devkit/schematics    : 17.1.1
   @angular/cli                  : 17.1.1
   @ionic/angular-toolkit        : 11.0.0

Capacitor:
   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : not installed
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : not installed globally

System:
   NodeJS : v18.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.4.0
   OS     : Windows 10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: resolves #28876

---------

## What is the current behavior?

When assigning `componentProps` as inputs to an Angular component, we do `Object.assign`. When using the newer Angular Signals API for inputs the value of an input is a function:

```js
myInput = input<string>('foo') // this is a function
```

The developer accesses the value of `myInput` in a template by doing `myInput()` since `myInput` is a function.

If a developer passes `componentProps: { myInput: 'bar' }` then the value of `myInput` is set to this string value, overriding the function. As a result, calling `myInput()` results in an error because `myInput` is a string not a function.

## What is the new behavior?

- Angular 14.1 introduced `setInput` which lets us hand off setting inputs to Angular. This will set input values properly even when using a Signals-based input.

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

As part of this `NavParams` has been removed as it is incompatible with the `setInput` API. The old `Object.assign` worked to allow devs to get all of the `componentProp` key value pairs via `NavParams` even if they are not defined as `Inputs`. Using `setInput` will now throw an error, so developers need to create an `@Input` for each parameter. This means that `NavParams` has no purpose and can safely be retired in favor of Angular's Input API. Not removing NavParms would make it difficult for us to support new Angular APIs such as this Signals-based input API.

## Other information

Dev build: `7.6.2-dev.11706205501.196a5433`

### CODE REVIEW

**Comment by thetaPC** [comment]
@liamdebeasi is this PR ready for review?

**Comment by liamdebeasi** [comment]
Not yet. This requires a breaking change that I want to run by the team first.

**Comment by liamdebeasi** [comment]
I'll close for now.

**Comment by ntorrey** [comment]
@brandyscarney Any hope Angular signals might be supported in future versions of Ionic?

**Comment by muuvmuuv** [comment]
The branch is merged into main recently and its name was 8.0, so I guess it will be in there? ^^

**Comment by brandyscarney** [comment]
I did not close this PR. It was automatically closed when the `feature-8.0` branch was deleted. Liam will have to open a new pull request to get this merged.

**Comment by EinfachHans** [comment]
@brandyscarney does someone has this in their mind, now where liam left?

**Comment by thetaPC** [comment]
A new [PR](https://github.com/ionic-team/ionic-framework/pull/29453) has been reopened! I recommend subscribing to it for more updates.

**Pull request closed without merging**
