### PR TITLE
feat(modal): add canDismiss property to manage modal dismissing

### LINKED ISSUE #22297: feat: canLeave event for overlays
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I want to add a CanLeave() Event on Overlays (mainly iOS card Style modal, but also for upcoming drawer) which should be somehow triggered while swiping. See attached Video of how native Web.de Mail-App handles this:

If nothing was typed in, i can just swipe to close the modal. If i did, the swipe doesn't go to the end and shows a Action Sheet after i released.

**Describe Preferred Solution**

I think this should automatically work if a CanDismiss Callback is set to the Modal Element. This should be able to parse a boolean, or better a Promise<boolean> or even better both.

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: resolves #22297

## What is the new behavior?

- Adds a new canDismiss property to give developers more control over when a modal is allowed to dismiss.
- Applies to regular, card, and sheet modals.
- swipeToClose is made redundant by this property and has been deprecated. It is scheduled to be removed in the next major release of Ionic.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Test

https://user-images.githubusercontent.com/2721089/157942666-b3ea2672-0d8b-4310-89e2-f2408821e167.MP4

**Review by amandaesmith3 — APPROVED** [review]

**Review by sean-perkins — APPROVED** [review]
Great work on this 🚀

**Comment by take** [comment]
@liamdebeasi @amandaejohnston @sean-perkins 

Hi I have a question here 🙋 

Looks like the new `canDismiss` property is the alternative? to the deprecated `swipeToClose`, but how can we implement the following situation with the new `canDismiss` property? 👀 (or is it possible?

* I want to allow the user to dismiss the modal except the swipe animation

I think this was possible by setting `swipeToClose` to false, but is this possible by using the `canDismiss` property? 🤔

**Comment by liamdebeasi** [comment]
Our documentation shows how to do this: https://ionicframework.com/docs/api/modal#prevent-swipe-to-close

**Comment by take** [comment]
@liamdebeasi thanks! ❤️

**Pull request merged**
