### PR TITLE
fix(refresher): ios native refresher now works in side menu

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Sometimes the scrollEl's clientHeight is zero because the containing element is hidden. This results in the refresher firing too early.

## What is the new behavior?

- Added a default MAX_PULL value in the event the content height is 0.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by EinfachHans** [comment]
The title of this PR is not correct i think 😃 And what about assigning `MAX_PULL` later? Where we knew the `scrollEl` must be visible. For example when the gesture starts?

**Comment by liamdebeasi** [comment]
Our PR titles and commit messages are designed to explain a concrete bug that a commit fixes, so just saying "ensure MAX_PULL is not 0" is not enough. In this case, this particular bug was discovered in a menu, so the title is going to reference the menu.

**Comment by liamdebeasi** [comment]
I'd rather not do DOM reads every time the user puts their finger/pointer down on the screen, but I can look into an alternative.

**Comment by EinfachHans** [comment]
Of course a fixed value is also not bad, but currently i like that it is based on the scroll height 😃 Maybe just save the scroll height on the first time the gesture starts if this is an option

**Pull request merged**
