### PR TITLE
chore(): update lerna to 5.3.0

### PR DESCRIPTION
**Pull request by JamesHenry**
Hi Folks 👋 

I'm one of the new maintainers of Lerna (via Nrwl).

As I noted on https://github.com/ionic-team/ionic-framework/pull/25497, I'm sorry that you had to initially downgrade from v5 back to v4.

I used Ionic's repo to troubleshoot a subtle difference between some of the implementation details we upgraded as part of v4->v5. Lerna uses a lot of packages produced by the npm team and in this case the package concerned with running lifecycle scripts needed to swapped out entirely after npm reimplemented it from scratch.

I added a missing piece of logic needed for the new package and released 5.3.0 of lerna just now, which addresses the issues you experienced before.

I even verified your full publishing flow locally by using a verdaccio instance instead of the real npm registry.

Please let me know if you have any questions or concerns! 🙏

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thank you very much! Apologies for not reaching out sooner. I saw your comment on my previous PR, but it slipped my mind. I'll give this a test and let you know how it goes.

**Comment by JamesHenry** [comment]
P.S. 

It is by no means a requirement, but one huge benefit you can opt into after this change goes in is to get lerna to delegate task running to Nx (instead of `p-map` and `p-queue` like it has done historically).

All you need to do over and above this PR is set `"useNx": true` in your `lerna.json` and everything will still work as it did before: `lerna run` will just get faster, have smart computation caching and allow for distributed task execution:

- https://lerna.js.org/docs/features/run-tasks
- https://lerna.js.org/docs/features/cache-tasks

Over and above that, the Nx Console VSCode extension is then able to analyze your lerna workspace and give you visualizations of how your projects relate to one another:

image

Again, all you need to do to get these things is set `"useNx": true` in your `lerna.json` (after merging this PR)

https://github.com/redwoodjs/redwood is an example of a popular OSS repo that is already leveraging these benefits with their lerna setup.

**Comment by JamesHenry** [comment]
Awesome, thanks for the fast review and testing @liamdebeasi! Feel free to reach out if you have any queries or concerns post-merge! @mhartington can always reach me on slack too 🙂

**Comment by liamdebeasi** [comment]
Merged. Thank you again!

**Pull request merged**
