### PR TITLE
chore(jsdoc): move comment on RadioGroup

### PR DESCRIPTION
**Pull request by alicewriteswrongs**
This converts a multiline comment (like `/**...*/`) above the `RadioGroup` component class to be a series of `//` comments instead. This is done to prevent the comment from being accidentally recognized as a JSDoc comment for the class when a Stencil version incorporating this change is installed:
https://github.com/ionic-team/stencil/commit/2e4b1fcdc0b3fd41928d27cf9ee525a15b02d617

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

If you build and install Stencil from `main` you'll see a change like this in `components.d.ts`:

```diff
diff --git a/core/src/components.d.ts b/core/src/components.d.ts
index 396879d6e9..49758b6613 100644
--- a/core/src/components.d.ts
+++ b/core/src/components.d.ts
@@ -2095,6 +2095,12 @@ export namespace Components {
          */
         "value"?: any | null;
     }
+    /**
+     * The Radio Group component mandates that only one radio button
+     * within the group can be selected at any given time. Since `ion-radio`
+     * is a shadow DOM component, it cannot natively perform this behavior
+     * using the `name` attribute.
+     */
     interface IonRadioGroup {
         /**
           * If `true`, the radios can be deselected.
@@ -3653,6 +3659,12 @@ declare global {
         prototype: HTMLIonRadioElement;
         new (): HTMLIonRadioElement;
     };
+    /**
+     * The Radio Group component mandates that only one radio button
+     * within the group can be selected at any given time. Since `ion-radio`
+     * is a shadow DOM component, it cannot natively perform this behavior
+     * using the `name` attribute.
+     */
     interface HTMLIonRadioGroupElement extends Components.IonRadioGroup, HTMLStencilElement {
     }
     var HTMLIonRadioGroupElement: {
@@ -6025,6 +6037,12 @@ declare namespace LocalJSX {
          */
         "value"?: any | null;
     }
+    /**
+     * The Radio Group component mandates that only one radio button
+     * within the group can be selected at any given time. Since `ion-radio`
+     * is a shadow DOM component, it cannot natively perform this behavior
+     * using the `name` attribute.
+     */
     interface IonRadioGroup {
         /**
           * If `true`, the radios can be deselected.
@@ -7283,6 +7301,12 @@ declare module "@stencil/core" {
             "ion-popover": LocalJSX.IonPopover & JSXBase.HTMLAttributes<HTMLIonPopoverElement>;
             "ion-progress-bar": LocalJSX.IonProgressBar & JSXBase.HTMLAttributes<HTMLIonProgressBarElement>;
             "ion-radio": LocalJSX.IonRadio & JSXBase.HTMLAttributes<HTMLIonRadioElement>;
+            /**
+             * The Radio Group component mandates that only one radio button
+             * within the group can be selected at any given time. Since `ion-radio`
+             * is a shadow DOM component, it cannot natively perform this behavior
+             * using the `name` attribute.
+             */
             "ion-radio-group": LocalJSX.IonRadioGroup & JSXBase.HTMLAttributes<HTMLIonRadioGroupElement>;
             "ion-range": LocalJSX.IonRange & JSXBase.HTMLAttributes<HTMLIonRangeElement>;
             "ion-refresher": LocalJSX.IonRefresher & JSXBase.HTMLAttributes<HTMLIonRefresherElement>;
```

This is no good! The comment:

https://github.com/ionic-team/ionic-framework/blob/a1580d89e2083ac94569db598e062d07f9083321/core/src/components/radio-group/radio-group.tsx#L7-L20

wasn't intended to be included that way.

## What is the new behavior?

This just changes the type of comment used in a comment immediately preceding a component class, to prevent the comment from being inadvertently used as a JSDoc comment.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sean-perkins** [comment]
@alicewriteswrongs if we moved this block inside the class declaration, would that also avoid this issue? I don't necessarily agree with formatting a multi-line comment into a series of single-line comments.

**Comment by alicewriteswrongs** [comment]
Yup, we can definitely do something like this:

```diff
diff --git a/core/src/components/radio-group/radio-group.tsx b/core/src/components/radio-group/radio-group.tsx
index 8dbdcaba87..91c465e3cf 100644
--- a/core/src/components/radio-group/radio-group.tsx
+++ b/core/src/components/radio-group/radio-group.tsx
@@ -4,16 +4,16 @@ import { Component, Element, Event, Host, Listen, Prop, Watch, h } from '@stenci
 import { getIonMode } from '../../global/ionic-global';
 import type { RadioGroupChangeEventDetail } from '../../interface';
 
-/**
- * The Radio Group component mandates that only one radio button
- * within the group can be selected at any given time. Since `ion-radio`
- * is a shadow DOM component, it cannot natively perform this behavior
- * using the `name` attribute.
- */
 @Component({
   tag: 'ion-radio-group',
 })
 export class RadioGroup implements ComponentInterface {
+  /**
+   * The Radio Group component mandates that only one radio button
+   * within the group can be selected at any given time. Since `ion-radio`
+   * is a shadow DOM component, it cannot natively perform this behavior
+   * using the `name` attribute.
+   */
   private inputId = `ion-rg-${radioGroupIds++}`;
   private labelId = `${this.inputId}-lbl`;
   private label?: HTMLIonLabelElement | null;
```

instead. Is that what you had in mind?

**Comment by sean-perkins** [comment]
I was thinking here: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/radio-group/radio-group.tsx#L94 since it is the manual implementation that the `name` attribute would have been responsible for.

**Comment by alicewriteswrongs** [comment]
ok cool that makes sense, just pushed that change

**Review by sean-perkins — APPROVED** [review]
Thank you for doing this! I merged in `main`, so CI should hopefully be passing after.

**Pull request merged**
