### PR TITLE
feat: ionCheck and ionUncheck for ion-checkbox

### PR DESCRIPTION
**Pull request by mahnuh**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19096 

## What is the new behavior?

- added ionCheck event to ion-checkbox which will be emitted when the checkbox is being checked
- added ionUncheck event to ion-checkbox which will be emitted when the checkbox is being unchecked

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

--

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! The `checked` property is provided in the detail of the `ionChange` event. Is there a reason you can't check for this?

```
const checkbox = document.querySelector('ion-checkbox');

checkbox.addEventListener('ionChange', (ev) => {
  console.log('Checked changed', ev.detail.checked);
});
```

Here's a Codepen example: https://codepen.io/brandyscarney/pen/ExYKaaX?editors=1011

**Comment by mahnuh** [comment]
Hey @brandyscarney,
sure, ionChange would work in most cases but as described in #19096 there are some cases where it doesn't. Basically when you want to determine if either the `checked` property changed because the user tapped on the checkbox or the model just changed. This is not possible with ionChange I guess, as it will be emitted in both cases?

**Comment by Gorgoroth** [comment]
@brandyscarney I agree, it makes sense to emit the checked and unchecked events. It's easy to do in this place, it's harder to handle the case of #19096 in business logic.

**Comment by mahnuh** [comment]
@brandyscarney just wondering if there are any updates on this?

**Comment by amandaejohnston** [comment]
Thanks for the PR! We appreciate the work you've put in. In the time that's passed, we've slated some changes for the upcoming Ionic 7 release that will solve the problems this PR is targeting. Namely, the `ionChange` event is being modified to only fire for user-committed changes.

Here is the RFC for this change in general: https://github.com/ionic-team/ionic-framework/discussions/25532
And here is the PR for `ion-checkbox` in particular, which has already been merged into the v7.0 branch and will be available in the upcoming major release: https://github.com/ionic-team/ionic-framework/pull/25923

As such, I'm going to go ahead and close this PR out. Thank you!

**Pull request closed without merging**
