### PR TITLE
feat(toggle): support label, placement, justify

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The new standalone toggle does not support labels, label placement, and control justification

## What is the new behavior?

- Adds base rendering of the toggle. I abstracted this to a render function so that both the legacy and modern toggles  can use it to avoid copy-and-paste mistakes.
- Added support for rendering a label
- Added support for controlling the label placement relative to the control with `labelPlacement`
- Added support for packing the label and control in a line with `justify`.
- Added tests to check label, label placement, justification, color prop, states, and usage in ion-item.
- Updated the internal implementation to make use of the new `--track-*` variables.
- I was also able to fix a longstanding Toggle RTL bug where it displayed incorrectly in Safari: https://github.com/ionic-team/ionic-framework/issues?q=is%3Aissue+is%3Aopen+toggle+rtl --> I pulled this out into a separate PR to go into `main`: https://github.com/ionic-team/ionic-framework/pull/26315 I will sync this branch once `feature-7.0` gets synced with `main`.

Note: This does not include active/focus/hover states nor does it include fixes required for shadow part customization. This will be done in a separate PR.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
> Some of the toggles in the legacy sizes test are also rendering strangely in RTL (some handles are shaped and/or positioned incorrectly) though I'm unsure at a glance whether it's the test itself that needs adjusting.

Which ones are shaped incorrectly? FWIW the "Custom Heights" toggles are intentionally customized to look kind of funky.

**Comment by amandaejohnston** [comment]
Highlighted the ones that look outright buggy in red:
toggles

**Comment by liamdebeasi** [comment]
Thanks, I fixed that in https://github.com/ionic-team/ionic-framework/pull/26314/commits/f74a7b651c53a9a142fb9baec632dc29bd49db1e. Also fixed in the `toggle-rtl` branch since it appeared on `main`.

**Comment by amandaejohnston** [comment]
Looks like the screenshots may need updating manually? I would expect the relevant sizing and onOffLabels tests to have failed with the fixes up.

**Comment by liamdebeasi** [comment]
Looking into why the textarea screenshot got updated, but otherwise this PR is good for a review.

**Review by sean-perkins — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Removing Amanda as a reviewer since she is out of office.

**Pull request merged**
