### PR TITLE
fix(overlays): trap focus inside overlay components except toast

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21647

## What is the new behavior?

- All overlay components (except ion-toast) now have their focus trapped inside the overlay component.
- This is to bring it in line with WCAG recommendations: https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mastergogo** [comment]
Please ensure focus is trapped for overlays even in devices for screen readers like talkback and voiceover.

**Comment by liamdebeasi** [comment]
Yes, it works when using screen readers.

**Comment by brandyscarney** [comment]
Looks great!

**Comment by mastergogo** [comment]
Hi @liamdebeasi is there any tentative timeline as to when this will be fixed? or in which ionic version it is scheduled to come, it is very critical for us from an accessibility standpoint?

**Comment by brandyscarney** [comment]
@mastergogo This was released in the `5.3.0` release: https://github.com/ionic-team/ionic-framework/releases/tag/v5.3.0

Updating to latest `5.3.1` should have this fix. 🙂

**Comment by mastergogo** [comment]
Hi @brandyscarney, thanks for responding, I updated the ionic core and checked alert-dialog with talkback, Talkback focus still goes behind and does not get trapped in the alert dialog. attached is the apk in a zip, below are the steps to reproduce:

Turn on the talkback from accessibility settings and Launch the app:
1) Open any recipe out of two by double-tapping.
2) Navigate to delete button and double-tap to delete
3) An alert dialog will appear, keep navigating, or swipe forward using talkback till the focus reaches the "okay" button.
4) keep swiping and you will notice that focus will not be trapped within the alert and go behind instead.

Let me know if more info is needed.
 
[app-debug.apk.zip](https://github.com/ionic-team/ionic-framework/files/5105029/app-debug.apk.zip)

**Comment by brandyscarney** [comment]
@mastergogo Thanks for the info! Could you please open a new issue for this?

**Comment by mastergogo** [comment]
Hi, @brandyscarney I have raised another issue #21946 along with apk and steps to reproduce.

**Comment by AlphaJuliettOmega** [comment]
This 'fix' might be related to an issue(bug) I'm having.

When spawning the SpinnerService from an ion-button click for example, the Overlay container for the Spinner service gets the focus, putting an ugly 1px outline around the entire application instead of _**leaving the focus on the clicked button**_ as it should.

I'm trying to figure out a Css work-around at the moment but I'm feeling doubtful.

**Pull request merged**
