### PR TITLE
chore(many): remove redundant :host selector from styles

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Components using the shadow DOM do not need to specify `:host` when targeting a child selector. `ion-datetime`, `ion-datetime-button`, `ion-picker-internal` and `ion-picker-column-internal` have redundant usage of `:host .element-selector`.

Issue URL: Relates to #25285

## What is the new behavior?

- Removes the `:host` selector in usages that target an explicit child selector in `ion-datetime`, `ion-datetime-button`, `ion-picker-internal` and `ion-picker-column-internal`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR blocks #25264

### CODE REVIEW

**Review by liamdebeasi — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Noticing some diffs: 
image

The calendar body diffs are fine (font changes from a previous fix that was not caught). But it looks like the arrow is misaligned.

**Comment by sean-perkins** [comment]
I'll run the update reference screenshot job against this branch to see if I can get the diffs to come through on CI as well. I'll obviously hold on merging until we can identify the cause. 

It is odd that just the removal of `:host` on the diff styles would cause any visual changes. It is possible that one of our mixins (e.g. the one identified in the open community PR) is producing incorrect output when the incoming selector doesn't explicitly contain `:host`.

**Review by amandaejohnston — COMMENTED** [review]
I'm still seeing the chevron misalignment Liam pointed out in his earlier comment, at least in the screenshot updates.

**Comment by liamdebeasi** [comment]
@sean-perkins Do we still want to merge this?

**Pull request closed without merging**
