### PR TITLE
Update input.tsx

### PR DESCRIPTION
**Pull request by eduardoroliveira**
Please add file type to input

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! `"file"` is not a valid value for `inputmode`. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode. Did you mean to change the `type` property instead?

**Comment by eduardoroliveira** [comment]
The type field documented to ion-input says it supports: `"date" | "email" | "number" | "password" | "search" | "tel" | "text" | "time" | "url"`. My suggestion was to expand to also support type `file`, as documented in here `https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file`.

Thanks

**Comment by liamdebeasi** [comment]
Ok in that case you will need to do two things:

1. Change the `type` property to support `"file"` and revert your `inputmode` change.
2. Run `npm run lint.fix && npm run build` from inside the `core` directory.

I need to check with the team to see if this is something we want to add. We do not currently have proper styles for `input[type="file"]`.

**Comment by liamdebeasi** [comment]
Thanks for the PR! We appreciate the work you put into creating this. After discussing with the team, we have decided not to accept this PR.

Our concern is that even if we accept `type="file"`, the interface that is rendered will still be incorrect when it comes to presenting a file upload field. We feel this will cause confusion as the interface that is rendered will still look like a text box.

I am going to close this PR, but if you are interested in seeing a file upload component/interface in Ionic please feel free to create a feature request. Thanks!

**Pull request closed without merging**
