### PR TITLE
fix(input): min/max compatibility with react-hook-form

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The type signature of the `min` and `max` properties on `IonInput` do not align with the typings for `input` from Stencil's public runtime, which clashes with `react-hook-form` usage when using this syntax:

```jsx
<IonInput {...register('email')} type="email"></IonInput>
```

Issue Number: #24489

## What is the new behavior?

- `min` has a type of `string | number`
- `max` has a type of `string | number`
- Type signatures of `IonInput` now align with the JSX extended types from Stencil public runtime and `react-hook-form`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by liamdebeasi — COMMENTED** [review]
A few concerns:

1. This changes the public API so would need to be released in a 6.x release.
2. Where do you see that the `max` and `min` attributes can be numbers in the HTML input spec? Looking at the spec, they appear to be strings and the browser converts them to numbers: https://html.spec.whatwg.org/multipage/input.html#the-min-and-max-attributes

**Comment by sean-perkins** [comment]
> A few concerns:
> 
> 1. This changes the public API so would need to be released in a 6.x release.
> 2. Where do you see that the `max` and `min` attributes can be numbers in the HTML input spec? Looking at the spec, they appear to be strings and the browser converts them to numbers: https://html.spec.whatwg.org/multipage/input.html#the-min-and-max-attributes

Sorry HTML spec was probably the wrong specification. The min/max typings through JSX & Stencil are typed as `number | string`:
- https://github.com/sean-perkins/stencil/blob/main/src/declarations/stencil-public-runtime.ts#L952
- https://github.com/sean-perkins/stencil/blob/main/src/declarations/stencil-public-runtime.ts#L949

This aligns with the types that react-hook-router uses:
- https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts#L151-L152

I think it's fine to hold this until a 6.x, but no other alternative exists. Implementers are currently having to do the following with react-hook-form and Ionic React:
```jsx
<IonInput {...register('email') as any} type="email"></IonInput>
```

I'll update the description to better reflect where these type changes come from.

**Review by amandaesmith3 — APPROVED** [review]
This LGTM. I think it's closer to a bug fix than a feature re: patch or minor release, but I could be persuaded 🤷‍♀️

**Review by liamdebeasi — APPROVED** [review]
Oh I see. In that case, yes I agree this is a fix. It should have been that way to begin with since it is how Stencil's types are configured.

**Pull request merged**
