### PR TITLE
fix(header): collapsible large title main header does not flicker on load

### LINKED ISSUE #27060: bug: Collapsible Large Titles Flicker
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

With version 7, the collapsed title flashes upon navigation

Does not happen with version 6

https://user-images.githubusercontent.com/15254340/228694868-c1a59b02-84a3-41eb-93ea-cae83d9294f7.mov

Please see video ^

### Expected Behavior

Would not flash, as in version 6

### Steps to Reproduce

upgrade to version 7

see flash on collapsed title

### Code Reproduction URL

_No response_

### Ionic Info

```
Ionic:

   Ionic CLI : 6.20.8

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: resolves #27060

---------

## What is the current behavior?

The main header is controlled by the header with `collapse="condense"` set: https://github.com/ionic-team/ionic-framework/blob/a04a11be3571faa99c751edc034462e94a977e95/core/src/components/header/header.tsx#L144

The collapse header will hide the main header and then show it once the user has scrolled enough. However, if the main header is rendered before the collapse header is rendered, then the main header will be visible for a brief moment before being hidden by the collapse header. This gives the perception of flicker that is reported on the linked issue.

## What is the new behavior?

- The main header will be hidden on load if it loads before the collapse header

The selector was written in a way such that once the collapse header loads, this CSS no longer applies (since the collapse header will add `.header-collapse-main` to the main header)

| `main` | branch |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/3cb11a57-e084-435a-89c2-e1c2afba04b1"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/c5caeb5e-3b33-4598-986f-bf097c46251c"></video> |

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Note: `:has` browser compat is still fairly new. However, it is available on both Chromium and WebKit browsers (and has been for at least a year): https://caniuse.com/?search=%3Ahas

Given that this bug is a fairly minor UI glitch (as opposed to something that would cause an app to crash or otherwise malfunction), I think this is an acceptable tradeoff. As time goes on this will become less of a concern as more users update their devices.

Dev build: `7.4.3-dev.11696365694.156f41d3`

### CODE REVIEW

**Comment by thetaPC** [comment]
I'm still seeing it with the dev build in one of the community's [repo](https://github.com/seanaguinaga/large-title-repro/tree/main). The flickering is happening on the [name](https://github.com/seanaguinaga/large-title-repro/blob/main/src/pages/ViewMessage.tsx).


https://github.com/ionic-team/ionic-framework/assets/13530427/3769be58-e467-4950-9cb8-adda6789faa4

**Comment by liamdebeasi** [comment]
That doesn't look like the same issue. This PR addresses an issue when the main header loads before the collapsing header, but in your demo the collapsing header is already loaded. I didn't look too much into why it was happening, but I did verify that the behavior is not being caused by my dev build.

**Comment by thetaPC** [comment]
> That doesn't look like the same issue. This PR addresses an issue when the main header loads before the collapsing header, but in your demo the collapsing header is already loaded. I didn't look too much into why it was happening, but I did verify that the behavior is not being caused by my dev build.

Do we have a ticket tracking this other issue?

**Comment by liamdebeasi** [comment]
No, but I'm also not confident this is an Ionic bug. I wasn't able to reproduce on my end in an Ionic starter app.

**Review by thetaPC — APPROVED** [review]
LGTM

**Pull request merged**
