### PR TITLE
test(angular): add timeout to avoid flaky value accessor test

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Occasionally the Angular E2E test suite will fail when validating if setting a value changes the form status of the control. 

Upon debugging this failing test, it appears to be the result of `ion-select`. After assigning the value, the control continues to have the `ion-invalid` class, which means that the value accessor never received the `ionChange` event.

Theory is that the value is set by Cypress before the component fully loads. By removing the safe guard, the event is still able to fire prior to the `componentDidLoad` resolving.

Issue URL: N/A

## What is the new behavior?

- Adds TODO statements for code that will be removed if the `ionChange` RFC is approved
- Adds timeout to the e2e test to reduce the flakiness of the value accessor test

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by amandaejohnston** [comment]
Would it be possible to have the test wait for the component to fully load instead?

**Comment by liamdebeasi** [comment]
Do you think the issue that what the `didInit` tries to avoid will be resolved with our proposed `ionChange` revisions?

**Comment by sean-perkins** [comment]
Yes, I think the checks were to work around the value accessors setting the value before the web component `defineCustomElement` finishes. 

With our proposed changes in the RFC, setting the value from the value accessor should not emit `ionChange`.

**Comment by liamdebeasi** [comment]
Can we keep the `didInit` patch for now and work around it in our test somehow? Then we can add a TODO to remove the `didInit` when the `ionChange` updates are merged (we can probably track these changes in the main ionChange ticket)

**Review by liamdebeasi — APPROVED** [review]
Thanks for taking care of this. Don't forget to change the commit subject when merging so this doesn't get logged as a bug.

**Comment by sean-perkins** [comment]
Thanks for the reminder; updated title + description, will wait for Amanda's review before merge 👍

**Review by amandaejohnston — APPROVED** [review]

**Pull request merged**
