### PR TITLE
fix(virtual-scroll): allow null in items prop

### PR DESCRIPTION
**Pull request by studioromeo**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Using the async pipe is considered best practice for angular projects.

When using the `async` pipe with `<ion-virtual-scroll>` with `strictTemplates` set to `true` in `tsconfig.json` we get this error `Type 'null' is not assignable to type 'any[] | undefined'.` during the build phase.

Issue Number: N/A

## What is the new behavior?

When setting `angularCompilerOptions.strictTemplates=true` in `tsconfig.json` the build fails because there is a type mismatch between async & [items]. This is because the return type of async can be `any[] | null` whereas [items] only accepts `any[] | undefined`. Adding null to the allowed types fixes the issue and allows async to be used with virtual scroll.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! Could you point me to an open issue that this change resolves? Or if there is no open issue, could you please reproduce this issue in a blank Ionic starter app and provide a link to the repo?

**Comment by studioromeo** [comment]
@liamdebeasi heya what do you think about this change?

**Comment by liamdebeasi** [comment]
Hey there! I need to spend some time reproducing the issue you described on my end first, but my initial research tells me this fix is probably fine.

**Comment by liamdebeasi** [comment]
For some reason the build never started here, so I made a new PR: https://github.com/ionic-team/ionic-framework/pull/23047

I am going to close this in favor of the linked PR, but I will be sure to give you co-author credit! Once the build passes on that PR I will merge it in.

Thanks!

**Comment by liamdebeasi** [comment]
I merged in the PR here https://github.com/ionic-team/ionic-framework/pull/23047. Thanks!

**Pull request closed without merging**
