### PR TITLE
fix(tabs): swipe back in tab goes to previous tab

### PR DESCRIPTION
**Pull request by yyesi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
https://github.com/ionic-team/ionic-framework/issues/21993

Issue Number: 21993

## What is the new behavior?

On tab click, I've used `root` RouterDirection, this helps to prevent swipe back when navigating around the tabs.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I haven't tested this 😸

### CODE REVIEW

**Comment by BerkeAras** [comment]
@yyesi Please **run tests** before creating a PR the **next time**.

**Comment by yyesi** [comment]
@BerkeAras CI has test runs and PRB has passed, meaning - no test failures.

**Comment by BerkeAras** [comment]
> @BerkeAras CI has test runs and PRB has passed, meaning - no test failures.

Thats why I said *next time*

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
Thanks for the PR! We are unable to accept this PR as it is not the correct solution to the problem. The problem here is that the swiper handler on Ionic React calls `this.context.goBack()` with no consideration as to whether or not it should go back.

This is what Ionic React does currently: https://github.com/ionic-team/ionic-framework/blob/91aaaab71a0df2feaec0b8edd94755fe5e733aee/packages/react-router/src/ReactRouter/StackManager.tsx#L128-L136

And for comparison, this is what Ionic Vue does: https://github.com/ionic-team/ionic-framework/blob/master/packages/vue/src/components/IonRouterOutlet.ts#L72-L88

In order for this PR to be accepted the changes should be made in that `canStart` function in Ionic React. Following what Ionic Vue does should be sufficient. Please let me know if you have any questions. Thanks!

**Comment by BerkeAras** [comment]
@liamdebeasi Is it related to #22342?

**Comment by liamdebeasi** [comment]
The issue with #22342 is that the swipe back gesture does not follow your touch movement, but the issue with #21993 is that redirect behavior with swiping back is incorrect. They are different enough that I think it warrants separate issues, but if we wanted to tackle them in the same PR I think that would be fine since both fixes would touch similar areas of the code.

**Comment by BerkeAras** [comment]
@liamdebeasi Okay, thanks. I am already working on a solution (it is not very easy ^^)

**Comment by yyesi** [comment]
@liamdebeasi thanks a lot for the review, fix should be straight forward, however I do not promise that I can implement this quick due to lack of free time (probably next weekend).

**Comment by liamdebeasi** [comment]
No problem! Let me know if you have any questions with implementation.

**Comment by yyesi** [comment]
Sorry won't be able to apply fix due to lack of free time, fix isn't straight forward as I initially thought.

**Pull request closed without merging**
