### PR TITLE
test(playwright): add new utilities for skipping tests

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL:  Internal ticket

There are many instances where we need to skip tests. For example, a particular test may only need to be run in a certain browser or on a certain mode. The current syntax, while functional, contains more boilerplate than is necessary. As a result, there is quite a bit of duplicate conditionals across tests.

## What is the new behavior?

- Introduces a new `skip` fixture on the `test` function. This fixture can be used to skip tests based on text direction, mode, or browser. See the readme in this PR for examples/docs.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Unresolved question: Do we want to require a reason with this syntax? Playwright does not require a reason when doing `test.skip`.

**Comment by amandaejohnston** [comment]
I think it'd be good if there were default/fallback reasons (with the param in the `skip` function being optional), since we use something like "This does not test RTL-specific logic" and "This feature is only available in x mode" for the majority of cases.

**Comment by liamdebeasi** [comment]
Updated, thanks!

**Review by amandaejohnston — APPROVED** [review]
~ We can probably update most of the existing skips to use the default values, but this LGTM as-is. Thanks for doing this!

**Review by sean-perkins — APPROVED** [review]

**Pull request merged**
