### PR TITLE
fix(angular): nested tabs now go to correct page

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23897

Each tabs instance listens for `ionTabButtonClick`, so if you click a tab button in a child tabs instance, the parent tabs instance will also see that event and try to navigate. But since the event was really only meant for the child tab, the parent tab will try to navigate to a non-existent route.

## What is the new behavior?

- When a tabs instance gets the ionTabButtonClick event it will prevent the event  from bubbling so any tabs higher up do not also receive this event and navigate to the wrong url

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by willmartindev — APPROVED** [review]

**Comment by kirillgroshkov** [comment]
FYI this broke our app. Also, it's inconsistent with the documentation: https://ionicframework.com/docs/api/tabs

Docs say that argument of `select` can be `string`. But in this PR (and in released `5.8.0`) it only accepts `CustomEvent` and breaks if you pass `string as any` to it.

We'll temporary pin to `5.7.0` until it's fixed.

image

**Comment by liamdebeasi** [comment]
See https://github.com/ionic-team/ionic-framework/issues/23952. We have a proposed fix in https://github.com/ionic-team/ionic-framework/issues/23952#issuecomment-923010019. It would be really helpful if you could test the dev build and let us know if it fixes the issue. Thanks!

**Comment by liamdebeasi** [comment]
Also the methods you see on the docs are for the vanilla JS `ion-tabs` component, not the `ion-tabs` component in Angular (Yes it is confusing). We are working on addressing this inconsistency in https://github.com/ionic-team/ionic-framework/issues/19918, but the `select` method not working with `HTMLIonTabElement` in Angular is not an issue caused by this PR.

**Comment by kirillgroshkov** [comment]
> See #23952. We have a proposed fix in [#23952 (comment)](https://github.com/ionic-team/ionic-framework/issues/23952#issuecomment-923010019). It would be really helpful if you could test the dev build and let us know if it fixes the issue. Thanks!

I unfortunately don't have time to test it, but looking at the PR code I *expect* that it'll fix it 👍

**Pull request merged**
