### PR TITLE
fix(toggle): rtl layout renders correctly in safari

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: Part of https://github.com/ionic-team/ionic-framework/issues/17012

While working on https://github.com/ionic-team/ionic-framework/pull/26314 I noticed this was still a problem. I fixed the problem in the v7 branch but wanted to pull this out to get this into v6.

## What is the new behavior?

- Toggle now renders correctly in RTL mode in Safari.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by amandaejohnston** [comment]
I had some comments on this over in https://github.com/ionic-team/ionic-framework/pull/26314, but we can handle discussion there 👀

**Comment by liamdebeasi** [comment]
Great catch! I fixed this in https://github.com/ionic-team/ionic-framework/pull/26315/commits/d52eec66b973aab54e9d54e352cdd6c1bc9afaab.

**Comment by liamdebeasi** [comment]
@amandaejohnston I updated the screenshots. I'm going to get this PR ready to merge before I update https://github.com/ionic-team/ionic-framework/pull/26314 with the changes.

**Review by amandaejohnston — COMMENTED** [review]
Looks like LTR was affected now; looking at `core/src/components/toggle/test/enable-on-off-labels/toggle.e2e.ts-snapshots/toggle-on-off-labels-dark-mode-diff-ios-ltr-Mobile-Safari-linux.png` for example, the "O" for unchecked toggles is missing, and the "I" for checked ones is off-center.

**Comment by liamdebeasi** [comment]
The problem was I kept targeting `.toggle-ltr` in addition to `.target-rtl`. However, the `toggle-ltr` class was never added (I only added it for RTL). I took this as a cue that I should always have both ltr and rtl classes.

**Review by sean-perkins — APPROVED** [review]

**Pull request merged**
