### PR TITLE
fix(menu): main content is not scrollable while swiping

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/21193

The `.menu-content-open` class prevents users from scrolling the content behind a menu when it is open: https://github.com/ionic-team/ionic-framework/blob/118b6ba25f9939939deb7d1782057fc062d266cf/core/src/css/core.scss#L266

However, it does not account for when users accidentally scroll the content while trying to drag the menu open because it is only added once the animation is complete. As a result, it is possible to scroll the content underneath the menu and have the menu gesture activate. This also causes the menu gesture performance to degrade significantly. 

## What is the new behavior?

- The `.menu-content-open` class is added before the open animation starts, preventing any accidental scrolls.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
It's easier to reproduce if you try it on an actual phone with touch capabilities rather than with touch simulation: https://github.com/ionic-team/ionic-framework/issues/21193#issuecomment-1470795283

I've found it easiest to repro on Chrome for Android if you try to swipe the menu open and then scroll in a circular motion like the video in the linked comment is doing.

**Review by amandaejohnston — APPROVED** [review]
Aha, just saw it. It does take a few tries haha. Looks good on the branch though. 👍

**Comment by lincolnthree** [comment]
Will test, thanks @liamdebeasi!

**Comment by lincolnthree** [comment]
Looks good here on V7.

**Pull request merged**
