### PR TITLE
fix(ion-item-sliding): open buttons immediately on first swipe  close…

### LINKED ISSUE #21579: bug: item-sliding requires multiple interactions when trying to open another item
**Ionic version:**
[] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
I used <ion-item-sliding> to achieve the function that user can dragged my ion-item to reveal the buttons. Now the behavior is that when 
I have opened one row to reveal the hidden buttons, and I continue to try open another one without closing the previous one. The first one is auto closed, but the second row is not open as expected. I need to drag again the second row to reveal the buttons.

**Expected behavior:**
The expected behavior should be that when I opened one row, I can drag another row to let first row auto close and open the new row simultaneously.

**Related code:**

-->

```
<div class="fund-box" *ngFor="let fund of funds ;let i=index"">
  <ion-item-sliding (ionDrag)="changeSliderIcon($event)" #slidingItem>
    <ion-item class="ion-no-margin ion-no-padding content-box" lines="none">
      <span class="rank rank{{i+1}}">{{i+1}}</span>
      <div class="remark-box">
        <div class="remark checked">{{fund.remark}}</div>
        <div class="tip">{{fund.remark_tip}}</div>
      </div>
      <div class="count-box left-slide">
        <div class="count">{{fund.count}}<span class="percent">%</span></div>
        <div class="tip">{{fund.count_tip}}</div>
      </div>
    </ion-item>
    <ion-item-options class="ion-align-items-stretch operation-box" lines="none">
      <div>
        <img src="/assets/images/home/love.png" class="love" (click)="onClickFavorite($event,slidingItem)"/>
      </div>
      <div class="setting" (click)="onClickSetting($event,slidingItem)" >{{fund.setting1}}<br>{{fund.setting2}}</div>
      <div class="buy" (click)="onClickBuy($event,slidingItem)" >{{fund.buy}}</div>
    </ion-item-options>
  </ion-item-sliding>
</div>
```

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

### PR DESCRIPTION
**Pull request by Sitronik**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
When swipe on the first element to open the buttons, the buttons open immediately, if  swipe on another element, the buttons will not open, they will open only if  swipe a second time

Issue Number: resolves #21579

## What is the new behavior?
Buttons open immediately after swiping on items

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by liamdebeasi — APPROVED** [review]
This is working great on my end, and `ion-item-sliding` is much more responsive now. Thank you!

I posted a dev build in https://github.com/ionic-team/ionic-framework/issues/21579 and would like to see some developers try it in their app before we merge this.

**Review by willmartindev — APPROVED** [review]
Agreed, this feels much better now! Thanks for the PR.

**Comment by Sitronik** [comment]
> This is working great on my end, and `ion-item-sliding` is much more responsive now. Thank you!
> 
> I posted a dev build in #21579 and would like to see some developers try it in their app before we merge this.

Ok, You are welcome, I will wait for the merge🙂, I hope it will not take long, thanks for your attention and a quick response 👍

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
