### PR TITLE
feat(datetime): add firstDayOfWeek prop

### LINKED ISSUE #23556: feat: Change Datetime Start of the Week
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

For me living in Germany it would be great to be able to change the Start of the Week day as it is Monday for us.

**Describe Solutions**

- `startOfTheWeek` Property
- automatically by locale if this is possible?

### PR DESCRIPTION
**Pull request by EinfachHans**
closes #23556

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The V6 Datetime Start of Week is currently always Sunday. This is not the correct value for every locale.

Issue Number: #23556 

## What is the new behavior?

- It seems like it is not possible to automatically determinate the StartOfWeek day by the locale
- Prop `startOfWeek` added (default is **0 - Sunday**)
- Functions `getDaysOfWeek` and `getDaysOfMonth` adjusted to respect the new Property

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

Screen Recording from the added Test:

### CODE REVIEW

**Review by willmartindev — CHANGES_REQUESTED** [review]
@EinfachHans 

Woah, great PR! Small change request: could you change the prop name from `startOfWeek` to `firstDayOfWeek`? This is more in line with upcoming JavaScript APIs and a couple other popular calendar implementations.

**Comment by EinfachHans** [comment]
@willmartindev of course 😊 i renamed the Prop

**Review by willmartindev — APPROVED** [review]
Nice job! It works great. 🚀

**Review by liamdebeasi — APPROVED** [review]
Great job! This is good to merge when tests pass.

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
