### PR TITLE
fix(checkbox, radio): change event interfaces correctly use TypeScript generics for value

### PR DESCRIPTION
**Pull request by osben**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hi there, 

Thanks for the PR! I noticed this seems to be the same code change as your other PR here: https://github.com/ionic-team/ionic-framework/pull/22953.

Could you please describe what issue this PR resolves?

**Comment by osben** [comment]
it helps describe the meaning to be expected and work in angular strict mode OR TSLint Rule: no-any

**Comment by liamdebeasi** [comment]
Thanks for the response! This PR looks good, but can you run `npm run build` from the `core` directory and push the changes that are generated? We need those build changes in order for the tests to pass here.

**Review by liamdebeasi — APPROVED** [review]

**Comment by liamdebeasi** [comment]
Merged. Thank you! I also added this fix for `ion-radio`.

**Pull request merged**
