### PR TITLE
Feat ion toggle toggle event

### PR DESCRIPTION
**Pull request by mahnuh**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The `ionChange` event will be emitted as soon as the toggle's value changes, whether that is because the toggle is being toggled manually or the value changes otherwise, programatically for example. At the moment from the `ionChange` event there is no way to determine if the value change happened manually or automatically.
This is basically the same issue as mentioned in PR #19097 for ion-checkbox.

## What is the new behavior?

This PR adds the `ionToggle` event which is only emitted when the toggle actually is being toggled by the user.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

--

### CODE REVIEW

**Comment by manucorporat** [comment]
I am not convinced about adding random APIs across inputs, we need to solve the problem for all inputs at once, and ship a consistent API for all components.

Maybe it could be a prop of ionChange itself, like "userInteraction" or "trigger"

**Comment by mahnuh** [comment]
This actually would be great and solve so many problems. Should I open an issue for that?

**Comment by liamdebeasi** [comment]
@manucorporat I'm wondering if the "trigger" would be good to add to all events for interactive components? I could see this being useful on `ion-checkbox` or `ion-radio` as well.

**Comment by tricki** [comment]
This event should probably also be emitted when the state is [changed by dragging](https://github.com/ionic-team/ionic/blob/master/core/src/components/toggle/toggle.tsx#L139).

This might also be useful for `ion-input`, in which case "trigger" might not be the ideal name.

**Pull request closed without merging**
