### PR TITLE
feat(refresher): add 'start' method

### LINKED ISSUE #16542: Programmaticaly beginRefresher for Refresher
# Feature Request

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI) : 4.4.0
System:
   NodeJS : v8.9.4
   npm    : 4.2.0
   OS     : Windows 10
```

**Describe the Feature Request**
As it was possible in Ionic 3.9.2, I would like to have a method to programaticaly begin refresh of a Refresher. I use it on every listPage to automatically load my data and show user that he can pulldown to refresh data

**Describe Preferred Solution**
A method on Refresher object which do the job.

**Describe Alternatives**
Here is my Ionic 3.9.2 code to do this

````
    public IonRefreshOpen(refresher: Refresher) {
        this._refresher = refresher;
        this._refresher._top = `${refresher.pullMin}px`;
        this._refresher._beginRefresh();
    }
````

Thanks for your answers

### PR DESCRIPTION
**Pull request by EinfachHans**
closes #16542 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #16542

## What is the new behavior?

- Add Method `start()` to manually begin refreshing

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kaloczikvn** [comment]
Nice PR, hopefully it will be added soon.

**Comment by davideas** [comment]
Hello, could you please publish this feature since it is ready since some months already?
We are eager waiting :-)

**Comment by liamdebeasi** [comment]
We are actively working through the PR backlog. We will review this PR soon and make a decision on whether or not we would like to merge it. We will post an update here when we have it.

Feature PRs typically take longer due to our internal design process (See https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#review-process-for-feature-prs for more info).

**Comment by liamdebeasi** [comment]
Hi @EinfachHans,

Apologies for the delay. We really appreciate all the hard work you put into creating this feature! The team recently reviewed this PR, and this is not something we are looking to merge at this time.

We would still like to add this feature to Ionic. However, we have some concerns about the proposed implementation. In particular, the proposed implementation does not work well with the [iOS Native Refresher style](https://ionicframework.com/docs/api/refresher#ios-usage) (the refresher appears on top of the content instead of having it shift the content down). We would like to explore other ways of resolving this issue prior to merging. We are not able to commit to solving this right now, so we are going to close this PR until the feature has been added to our roadmap.

We realize this may not be the resolution you were hoping for. Whenever this feature does make it into the codebase, we will give you co-author credit. Thanks!

**Pull request closed without merging**
