### PR TITLE
fix(item): only add click events to clickable items

### LINKED ISSUE #22011: bug: ion-item being read as clickable by screen reader
**Ionic version:**

[ ] **4.x**
[x] **5.x** (Seems to have been introduced with 5.3.2)

**Current behavior:**

ion-item when used in a page is read as clickable. This was first noticed with the release of version 5.3.2

**Steps to reproduce:**
Can be verified from:

https://ionicframework.com/docs/demos/api/item/index.html?ionic:mode=ios

**Other information:**

ion-items-clicable

### PR DESCRIPTION
**Pull request by brandyscarney**
Dev build: `5.5.0-dev.202010301640.9336349`

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: fixes #22011

## What is the new behavior?

Correctly announce items for screen readers, don't announce clickable when it is not

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kensodemann — APPROVED** [review]
Tested in a couple different apps. Does not break anything that I have found.
I was not able to test in NVDA to see if it fixed the issue there, but had no issues in the apps I tried it in.

LGTM, I am fine with merging it.

**Review by liamdebeasi — COMMENTED** [review]
My only concern about this is that we are making the click handler not reactive. If an item loads with no inputs then adds an input after a delay, this delegatesFocus function will never fire.

I can't imagine this is a common use case, but this PR would break that behavior.

**Comment by brandyscarney** [comment]
I fixed Liam's concerns with adding an input later on. The event listener is now added in the `componentDidUpdate` only if it has not already been added. Dev build for testing `5.5.0-dev.202010301640.9336349`. We need to test out that it doesn't break the fix for https://github.com/ionic-team/ionic-framework/issues/21509.

**Review by liamdebeasi — APPROVED** [review]
Other than the removeEventListener change we talked about offline, this looks good to go

**Pull request merged**
