### PR TITLE
Ion nav getbyindex

### PR DESCRIPTION
**Pull request by ogoguel**
#### Short description of what this resolves:

In the ion-nav component, if there are methods to access the view by index (getByIndex), there's no way to know the number of available views

#### Changes proposed in this pull request:

Added the length() @method 

**Ionic Version**:
 
4.10.3

**Fixes**: #

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening this PR. Would you be able to run `npm run lint` on your files? It's causing the build to fail. Thanks!

**Comment by liamdebeasi** [comment]
Sorry, forgot to also ask -- Can you run `npm run build`? This generates updated api files

**Comment by brandyscarney** [comment]
I'm not sure why this build is still failing. @ogoguel Was the repository cloned awhile ago? Could you try running the following *from inside the core directory*:

```
rm -rf node_modules/
npm i
npm run build
```

And seeing if there are any changes that come up?

**Comment by ogoguel** [comment]
Did what you suggested, @brandyscarney, but did not encounter any error while locally building the core component...

This repo has been cloned about 3 years ago when I first submitted some PR to you guys: is there a way to resync properly with your master repo ?

**Comment by liamdebeasi** [comment]
@ogoguel,

Since you PR is relatively simple, I think it might be easiest to just check out a fresh copy of Ionic and copy your changes over. Once you do that, run `npm run lint.fix` and `npm run build`. 

Let me know if you have any questions!

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay in reviewing this. We really appreciate the hard work you put into creating this PR. The team recently reviewed this, and this is not something we are looking to merge at this time. Given the age of the PR, we would prefer to start with a feature request to better understand the use case. As a result, we are going to close this PR for now.

I realize this may not be the resolution you were hoping for. If this is an important feature for your use case, I recommend opening a feature request. Thank you!

**Pull request closed without merging**
