### PR TITLE
fix(popover): only focus trap ion-item children

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

`ion-popover` has an internal key event handler for focusing between ion-item children elements. This handler conflicts with elements that have their own keyboard interactions, such as a HTML textarea element. 

Issue URL: #24633

## What is the new behavior?

- `ion-popover` only handles keyboard interactions when the active element is an `ion-item`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `6.0.15-dev.11649448530.1093d192`

### CODE REVIEW

**Review by amandaesmith3 — APPROVED** [review]

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
This regresses a behavior in `ion-popover`. In `main`, opening a popover and pressing the down arrow key will focus the first `ion-item`. In this branch, pressing the down arrow key does nothing. You can test in `/src/components/popover/test/nested`.

Maybe we need to change where this `ion-item` check is? (Also can we add a test for this behavior?)

**Comment by sean-perkins** [comment]
@liamdebeasi good catch 👍  I updated the logic so that keyboard navigation will happen for both when the popover host has focus or the `ion-item` within it. 

The previous tests were only verifying that `tab` set focus to the first item. I left that test as-is and added a new test that verifies that `ArrowDown` also focuses the first `ion-item`.

**Review by liamdebeasi — APPROVED** [review]
Great job! Can we make a dev build and provide it on the issue thread before merging?

**Comment by liamdebeasi** [comment]
@sean-perkins Doesn't look like we got any feedback from community. I am happy with the PR, and sounds like Amanda is too. Feel free to merge if you are ready to ship this.

**Pull request merged**
