### PR TITLE
feat: range, add reference point to start range slider at #24348

### PR DESCRIPTION
**Pull request by sachingarg05**
Added property barActiveStart. bar-active is shown between `barActiveStart` and knob for single knob range-bar. By default `barActiveStart` is set to `min` (Minimum integer value of the range).

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the new behavior?
Details were discussed in issue Number: #24348

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

md:
image
ios:
image

### CODE REVIEW

**Review by sean-perkins — COMMENTED** [review]
Awesome, thanks for this PR 👍 

Could you add an e2e test here: https://github.com/ionic-team/ionic-framework/tree/main/core/src/components/range/test (create a new folder) for this feature?

You can look at the other `e2e.ts` files for an example. We are just looking to have an example of this feature and to capture any visual regressions with this feature moving forward.

**Comment by sachingarg05** [comment]
Added a test in core/src/components/range/test/bar-active

md:
image

ios:
image

**Comment by sachingarg05** [comment]
Is this pull request OK for merging or does it need any changes?

**Comment by sachingarg05** [comment]
I was hoping to see this merged for 6.1.x release. Is there anything I can help with to get this merged?

**Comment by liamdebeasi** [comment]
The feature did not make it into the 6.1.0 release, but it is planned for a future release. We are scheduling time for a code review. A team member will leave feedback on this PR when they have it.

**Comment by sachingarg05** [comment]
Can someone from Ionic team please take a look at this? Really looking forward to see this get merged.

**Comment by sachingarg05** [comment]
Thanks for the update. Will be happy to help with any further changes that might be needed to get this merged.

**Comment by sean-perkins** [comment]
@sachingarg05 thank you so much for this PR contribution. 

I'm going to close this in favor of #25598. I will give you co-authored-by credit with that PR is reviewed & merged. We are planning on having this included in the 6.2.0 release.

Thank you!

**Pull request closed without merging**
