### PR TITLE
fix(label): keep color when focused on a floating or stacked label

### PR DESCRIPTION
**Pull request by topalavlad**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
When a stacked label with `color` attribute set is focused, it switches color to primary (only on MD)

Issue Number: #18531

## What is the new behavior?
A stacked label with `color` attribute set will keep its color when focused

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandyscarney — DISMISSED** [review]
Thank you for the PR! Unfortunately this will remove the default behavior of changing the label to primary on focus. The fix for this is likely updating the following to check for `:not(.ion-color)` on the label:

```
:host(.item-has-focus:not(.ion-color)) ::slotted(.label-stacked),
:host(.item-has-focus:not(.ion-color)) ::slotted(.label-floating) {
  color: $label-md-text-color-focused;
}

:host-context(.item-has-focus).label-stacked,
:host-context(.item-has-focus).label-floating {
  color: $label-md-text-color-focused;
}
```

**Comment by topalavlad** [comment]
I have updated the code but don't you think this request might have unexpected effects for people who were counting on primary color always being used for focused items?

**Comment by brandyscarney** [comment]
@topalavlad No this looks good! I think this is the correct CSS for the label, and expected behavior. The only issue seems to be that the highlight color for the bottom of the item is still using primary. I'm thinking we need to pass the label color up somehow.

**Review by brandyscarney — APPROVED** [review]

**Comment by brandyscarney** [comment]
Thanks so much for this PR! 😊 Sorry it took so long to get in.

**Pull request merged**
