### PR TITLE
fix(input): floating label works correctly with long text and notch

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

During testing, I noticed that my implemented of the notch in the MD outline was incorrect, causing the gap to be much wider than necessary when using longer labels.

I also noticed that long label texts do not flow correctly in the container.

## What is the new behavior?

- Long labels are now correctly truncated so they do not break the input layout
- Revamped how we create the notch in the MD outline style so the gap is correctly sized.
- Added tests

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
@amandaejohnston This is the same PR as https://github.com/ionic-team/ionic-framework/pull/26252, but I accidentally merged it when I meant to merge https://github.com/ionic-team/ionic-framework/pull/26248 (I had both open in tabs next to each other 🙃)

**Review by amandaejohnston — COMMENTED** [review]
For `stacked`, the label truncation seems to work differently between `md` and `ios`, unlike `floating`:
ios mode
md mode
Was that intentional?

**Comment by liamdebeasi** [comment]
No, that was some extra code I copied from the floating label. I fixed that in https://github.com/ionic-team/ionic-framework/pull/26273/commits/336d8092445573e540a785a88f7b10ad41a12f5a and am updating screenshots.

**Review by amandaejohnston — APPROVED** [review]
Looking good now 👍 Thank you!

**Pull request merged**
