### PR TITLE
fix(segment): position segment center with buttons

### PR DESCRIPTION
**Pull request by brandyscarney**
fixes https://github.com/ionic-team/ionic/issues/21037

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Segment was being pushed over based on the existence of buttons, this is different than the native iOS behavior

## What is the new behavior?

| `master` | `branch` |
| ---| ---|
| master | branch |

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
This is good to merge if screenshot passes

**Comment by brandyscarney** [comment]
Screenshot has bad mismatches https://screenshot.ionicframework.com/45d03ba/d8ed03e

**Comment by liamdebeasi** [comment]
Linking with issue: https://github.com/ionic-team/ionic/issues/21037

**Comment by brandyscarney** [comment]
This PR needs a design decision. The only way I can find to fix it is to absolutely position it, but then it will mess up the height for icon top / icon bottom segments since those are taller. The best solution here may be to automatically increase the toolbar height for segments with icon top/bottom but if a user needs it any taller than that they would have to know to set the toolbar height.

**Comment by liamdebeasi** [comment]
Not merging at the moment, so I am going to close this for now. Please feel free to reopen when ready for review/merging!

**Pull request closed without merging**
