### PR TITLE
refactor(swiper): removed duplicate code

### PR DESCRIPTION
**Pull request by lucasrleandro**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

Duplicate code.

## What is the new behavior?

Code optimized, duplicate rows removed.
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR. We appreciate the contribution to Ionic. Can you please describe what issue this PR solves?

**Comment by lucasrleandro** [comment]
Hello!
Its not an issue, its only a refactoring. Should I create an issue for it?
I was taking a look at the code and saw this refactoring opportunity.


Em qui., 18 de nov. de 2021 às 16:29, Liam DeBeasi ***@***.***>
escreveu:

**Comment by liamdebeasi** [comment]
Thanks! So that `swiper.bundle.js` file is built from the Swiper npm package, so whenever we publish a new build of Ionic the changes in this PR are going to get wiped out unfortunately.

Additionally, we have deprecated `ion-slides` in favor of developers installing Swiper.js directly, so we have a freeze on new development in `ion-slides`.

One thing you might want to try is to see if the same refactoring opportunity is available in the latest version of Swiper and make your change there: https://github.com/nolimits4web/Swiper. Does this address your concern?

**Comment by lucasrleandro** [comment]
Sure! My mistake!
I will do it! Thank you!!



Em qui., 18 de nov. de 2021 às 16:50, Liam DeBeasi ***@***.***>
escreveu:

**Comment by liamdebeasi** [comment]
No worries!

I am going to close this PR out. Thanks again for the contribution!

**Pull request closed without merging**
